// Code generated by tinybind HTML templates; DO NOT EDIT.

package pages

import (
	"html"
	"io"
	"net/http"
	"strconv"
	"strings"

	runtimehtmlbind "github.com/shibukawa/tinybind-go/htmlbind"
)

type HTML func(http.ResponseWriter, *http.Request) error
type TrustedHTML string
type TrustedCSS string
type TrustedJavaScript string
type ScriptJSON string

func _tinybindWrite(w io.Writer, value string) error { _, err := io.WriteString(w, value); return err }
func _tinybindEscape(value string) string            { return html.EscapeString(value) }
func _tinybindBool(value bool) string                { return strconv.FormatBool(value) }
func _tinybindInt(value int) string                  { return strconv.Itoa(value) }
func _tinybindFloat(value float64) string            { return strconv.FormatFloat(value, 'g', -1, 64) }

func _tinybindJSONQuote(value string) string {
	const hex = "0123456789abcdef"
	var out strings.Builder
	out.WriteByte('"')
	for _, r := range value {
		switch r {
		case '"':
			out.WriteString("\\\"")
		case '\\':
			out.WriteString("\\\\")
		case '\b':
			out.WriteString("\\b")
		case '\f':
			out.WriteString("\\f")
		case '\n':
			out.WriteString("\\n")
		case '\r':
			out.WriteString("\\r")
		case '\t':
			out.WriteString("\\t")
		case '<':
			out.WriteString("\\u003c")
		case '>':
			out.WriteString("\\u003e")
		case '&':
			out.WriteString("\\u0026")
		case '\u2028':
			out.WriteString("\\u2028")
		case '\u2029':
			out.WriteString("\\u2029")
		default:
			if r < 0x20 {
				out.WriteString("\\u00")
				out.WriteByte(hex[byte(r)>>4])
				out.WriteByte(hex[byte(r)&15])
			} else {
				out.WriteRune(r)
			}
		}
	}
	out.WriteByte('"')
	return out.String()
}

type User struct {
	Name string
}

func renderBadge(w http.ResponseWriter, r *http.Request, label string, children HTML) error {
	if err := _tinybindWrite(w, "\n<span class=\"badge\"><strong>"); err != nil {
		return err
	}
	if err := _tinybindWrite(w, _tinybindEscape(label)); err != nil {
		return err
	}
	if err := _tinybindWrite(w, "</strong>"); err != nil {
		return err
	}
	if err := children(w, r); err != nil {
		return err
	}
	if err := _tinybindWrite(w, "</span>\n"); err != nil {
		return err
	}
	return nil
}

func Card(w http.ResponseWriter, r *http.Request, user User) (_tinybindErr error) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	var _tinybindClose func() error
	w, _tinybindClose, _tinybindErr = runtimehtmlbind.PrepareResponse(w, r)
	if _tinybindErr != nil {
		return _tinybindErr
	}
	defer func() {
		if err := _tinybindClose(); _tinybindErr == nil {
			_tinybindErr = err
		}
	}()
	if err := _tinybindWrite(w, "\n"); err != nil {
		return err
	}
	if err := renderBadge(
		w,
		r,
		user.Name,
		func(w http.ResponseWriter, r *http.Request) error {
			if err := _tinybindWrite(w, "<em>member</em>"); err != nil {
				return err
			}
			return nil
		},
	); err != nil {
		return err
	}
	if err := _tinybindWrite(w, "\n"); err != nil {
		return err
	}
	return nil
}
