package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"strconv"
	"strings"
)

// Emit generates Go source for type-specific binders, writers, and JSON codecs.
// The output does not import "reflect".
func Emit(plan *PackagePlan) ([]byte, error) {
	if plan == nil {
		return nil, fmt.Errorf("nil plan")
	}
	var b bytes.Buffer
	b.WriteString("// Code generated by httpbinder; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", plan.Package)

	needRegexp := false
	for _, t := range plan.Types {
		for _, f := range t.Fields {
			if f.Check.Pattern != "" {
				needRegexp = true
				break
			}
		}
		if needRegexp {
			break
		}
	}

	b.WriteString("import (\n")
	b.WriteString("\t\"encoding/json\"\n")
	b.WriteString("\t\"io\"\n")
	if needRegexp {
		b.WriteString("\t\"regexp\"\n")
	}
	b.WriteString("\t\"net/http\"\n\n")
	b.WriteString("\t\"github.com/shibukawa/httpbind-go\"\n")
	b.WriteString(")\n\n")
	b.WriteString("type jsonRaw = json.RawMessage\n\n")

	for _, t := range plan.Types {
		for _, f := range t.Fields {
			if f.Check.Pattern == "" {
				continue
			}
			fmt.Fprintf(&b, "var checkPattern%s%s = regexp.MustCompile(%s)\n", t.Name, f.Name, strconv.Quote(f.Check.Pattern))
		}
	}
	if needRegexp {
		b.WriteString("\n")
	}

	b.WriteString("func init() {\n")
	for _, t := range plan.Types {
		fmt.Fprintf(&b, "\thttpbinder.RegisterBind[%s](bind%s)\n", t.Name, t.Name)
		fmt.Fprintf(&b, "\thttpbinder.RegisterWrite[%s](write%s)\n", t.Name, t.Name)
		fmt.Fprintf(&b, "\thttpbinder.RegisterDecode[%s](decode%sBytes)\n", t.Name, t.Name)
		fmt.Fprintf(&b, "\thttpbinder.RegisterEncode[%s](encode%s)\n", t.Name, t.Name)
	}
	b.WriteString("}\n\n")

	// Index types for nested encode helpers
	types := map[string]TypePlan{}
	for _, t := range plan.Types {
		types[t.Name] = t
	}

	for _, t := range plan.Types {
		emitDecodeJSON(&b, t, types)
		emitEncode(&b, t, types)
		emitBinder(&b, t, types)
		emitWriter(&b, t, types)
	}

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return b.Bytes(), fmt.Errorf("format generated code: %w\n%s", err, b.String())
	}
	return formatted, nil
}

func emitDecodeJSON(b *bytes.Buffer, t TypePlan, types map[string]TypePlan) {
	fmt.Fprintf(b, "func decode%sBytes(data []byte) (%s, error) {\n", t.Name, t.Name)
	fmt.Fprintf(b, "\treturn decode%sJSON(json.RawMessage(data))\n}\n\n", t.Name)

	fmt.Fprintf(b, "func decode%sJSON(raw json.RawMessage) (%s, error) {\n", t.Name, t.Name)
	fmt.Fprintf(b, "\tvar out %s\n", t.Name)
	if documentFieldCount(t) == 0 {
		// No JSON document fields (e.g. cookie/path-only models).
		b.WriteString("\t_ = raw\n")
		b.WriteString("\treturn out, nil\n}\n\n")
		return
	}
	b.WriteString("\tm, err := httpbinder.RawJSONMap(raw)\n")
	b.WriteString("\tif err != nil {\n\t\treturn out, err\n\t}\n")
	emitFillFromJSONMap(b, t, types, "m", "\t")
	b.WriteString("\treturn out, nil\n}\n\n")
}

func documentFieldCount(t TypePlan) int {
	n := 0
	for _, f := range t.Fields {
		if isDocumentField(f) {
			n++
		}
	}
	return n
}

func isDocumentField(f FieldPlan) bool {
	if f.Source == SourcePath || f.Source == SourceHeader || f.Source == SourceCookie || f.Source == SourceMethod || f.Source == SourceQuery {
		return false
	}
	if f.Kind == "file" {
		return false
	}
	return f.Source == SourceInput || f.Source == SourcePayload
}

// emitFillFromJSONMap assigns fields of t from map variable mapVar into out.
func emitFillFromJSONMap(b *bytes.Buffer, t TypePlan, types map[string]TypePlan, mapVar, prefix string) {
	for _, f := range t.Fields {
		if !isDocumentField(f) || f.IsRest() {
			continue
		}
		key := f.JSON
		if key == "" || key == "*" {
			key = f.Wire
		}
		fmt.Fprintf(b, "%sif raw, ok := %s[%q]; ok {\n", prefix, mapVar, key)
		emitAssignFromRaw(b, f, types, "raw", prefix+"\t", "out."+f.Name, true)
		fmt.Fprintf(b, "%s}\n", prefix)
	}
	// rest fields
	for _, f := range t.Fields {
		if !f.IsRest() {
			continue
		}
		exclude := bodyWireExclude(t)
		switch f.Kind {
		case KindRestAny:
			fmt.Fprintf(b, "%s{\n", prefix)
			fmt.Fprintf(b, "%s\trm, err := httpbinder.RestJSONAny(%s, []string{%s})\n", prefix, mapVar, quoteStringList(exclude))
			fmt.Fprintf(b, "%s\tif err != nil {\n%s\t\treturn out, err\n%s\t}\n", prefix, prefix, prefix)
			fmt.Fprintf(b, "%s\tout.%s = rm\n", prefix, f.Name)
			fmt.Fprintf(b, "%s}\n", prefix)
		case KindRestRaw:
			fmt.Fprintf(b, "%sout.%s = httpbinder.RestJSONRaw(%s, []string{%s})\n", prefix, f.Name, mapVar, quoteStringList(exclude))
		}
	}
}

func emitAssignFromRaw(b *bytes.Buffer, f FieldPlan, types map[string]TypePlan, rawVar, prefix, dest string, returnOut bool) {
	ret := "return out, "
	if !returnOut {
		ret = "return "
	}
	switch f.Kind {
	case "string":
		fmt.Fprintf(b, "%sv, err := httpbinder.DecodeJSONString(%s)\n", prefix, rawVar)
		fmt.Fprintf(b, "%sif err != nil {\n%s\t%shttpbinder.BindError(%q, \"payload\", \"invalid string\")\n%s}\n", prefix, prefix, ret, f.Wire, prefix)
		fmt.Fprintf(b, "%s%s = v\n", prefix, dest)
	case "int":
		fmt.Fprintf(b, "%sv, err := httpbinder.DecodeJSONInt(%s)\n", prefix, rawVar)
		fmt.Fprintf(b, "%sif err != nil {\n%s\t%shttpbinder.BindError(%q, \"payload\", \"invalid int\")\n%s}\n", prefix, prefix, ret, f.Wire, prefix)
		fmt.Fprintf(b, "%s%s = v\n", prefix, dest)
	case "int64":
		fmt.Fprintf(b, "%sv, err := httpbinder.DecodeJSONInt64(%s)\n", prefix, rawVar)
		fmt.Fprintf(b, "%sif err != nil {\n%s\t%shttpbinder.BindError(%q, \"payload\", \"invalid int64\")\n%s}\n", prefix, prefix, ret, f.Wire, prefix)
		fmt.Fprintf(b, "%s%s = v\n", prefix, dest)
	case "bool":
		fmt.Fprintf(b, "%sv, err := httpbinder.DecodeJSONBool(%s)\n", prefix, rawVar)
		fmt.Fprintf(b, "%sif err != nil {\n%s\t%shttpbinder.BindError(%q, \"payload\", \"invalid bool\")\n%s}\n", prefix, prefix, ret, f.Wire, prefix)
		fmt.Fprintf(b, "%s%s = v\n", prefix, dest)
	case "float64":
		fmt.Fprintf(b, "%sv, err := httpbinder.DecodeJSONFloat64(%s)\n", prefix, rawVar)
		fmt.Fprintf(b, "%sif err != nil {\n%s\t%shttpbinder.BindError(%q, \"payload\", \"invalid float64\")\n%s}\n", prefix, prefix, ret, f.Wire, prefix)
		fmt.Fprintf(b, "%s%s = v\n", prefix, dest)
	case KindStruct:
		fmt.Fprintf(b, "%sv, err := decode%sJSON(%s)\n", prefix, f.TypeName, rawVar)
		fmt.Fprintf(b, "%sif err != nil {\n%s\t%serr\n%s}\n", prefix, prefix, ret, prefix)
		fmt.Fprintf(b, "%s%s = v\n", prefix, dest)
	case KindSlice:
		emitAssignSliceFromRaw(b, f, rawVar, prefix, dest, ret)
	case KindMap:
		emitAssignMapFromRaw(b, f, rawVar, prefix, dest, ret)
	case "file":
		// file cannot be decoded from JSON object fields
	}
}

func emitAssignSliceFromRaw(b *bytes.Buffer, f FieldPlan, rawVar, prefix, dest, ret string) {
	switch f.ElemKind {
	case "string":
		fmt.Fprintf(b, "%sv, err := httpbinder.DecodeJSONStringSlice(%s)\n", prefix, rawVar)
		fmt.Fprintf(b, "%sif err != nil {\n%s\t%serr\n%s}\n", prefix, prefix, ret, prefix)
		fmt.Fprintf(b, "%s%s = v\n", prefix, dest)
	case "int":
		fmt.Fprintf(b, "%sv, err := httpbinder.DecodeJSONIntSlice(%s)\n", prefix, rawVar)
		fmt.Fprintf(b, "%sif err != nil {\n%s\t%serr\n%s}\n", prefix, prefix, ret, prefix)
		fmt.Fprintf(b, "%s%s = v\n", prefix, dest)
	case "int64":
		fmt.Fprintf(b, "%sv, err := httpbinder.DecodeJSONInt64Slice(%s)\n", prefix, rawVar)
		fmt.Fprintf(b, "%sif err != nil {\n%s\t%serr\n%s}\n", prefix, prefix, ret, prefix)
		fmt.Fprintf(b, "%s%s = v\n", prefix, dest)
	case "bool":
		fmt.Fprintf(b, "%sv, err := httpbinder.DecodeJSONBoolSlice(%s)\n", prefix, rawVar)
		fmt.Fprintf(b, "%sif err != nil {\n%s\t%serr\n%s}\n", prefix, prefix, ret, prefix)
		fmt.Fprintf(b, "%s%s = v\n", prefix, dest)
	case "float64":
		fmt.Fprintf(b, "%sv, err := httpbinder.DecodeJSONFloat64Slice(%s)\n", prefix, rawVar)
		fmt.Fprintf(b, "%sif err != nil {\n%s\t%serr\n%s}\n", prefix, prefix, ret, prefix)
		fmt.Fprintf(b, "%s%s = v\n", prefix, dest)
	case KindStruct:
		fmt.Fprintf(b, "%sarr, err := httpbinder.RawJSONArray(%s)\n", prefix, rawVar)
		fmt.Fprintf(b, "%sif err != nil {\n%s\t%serr\n%s}\n", prefix, prefix, ret, prefix)
		fmt.Fprintf(b, "%sslice := make([]%s, 0, len(arr))\n", prefix, f.TypeName)
		fmt.Fprintf(b, "%sfor _, el := range arr {\n", prefix)
		fmt.Fprintf(b, "%s\titem, err := decode%sJSON(el)\n", prefix, f.TypeName)
		fmt.Fprintf(b, "%s\tif err != nil {\n%s\t\t%serr\n%s\t}\n", prefix, prefix, ret, prefix)
		fmt.Fprintf(b, "%s\tslice = append(slice, item)\n", prefix)
		fmt.Fprintf(b, "%s}\n", prefix)
		fmt.Fprintf(b, "%s%s = slice\n", prefix, dest)
	}
}

func emitAssignMapFromRaw(b *bytes.Buffer, f FieldPlan, rawVar, prefix, dest, ret string) {
	switch f.ElemKind {
	case "string":
		fmt.Fprintf(b, "%sv, err := httpbinder.DecodeJSONMapStringString(%s)\n", prefix, rawVar)
		fmt.Fprintf(b, "%sif err != nil {\n%s\t%serr\n%s}\n", prefix, prefix, ret, prefix)
		fmt.Fprintf(b, "%s%s = v\n", prefix, dest)
	case KindStruct:
		fmt.Fprintf(b, "%sobj, err := httpbinder.RawJSONMap(%s)\n", prefix, rawVar)
		fmt.Fprintf(b, "%sif err != nil {\n%s\t%serr\n%s}\n", prefix, prefix, ret, prefix)
		fmt.Fprintf(b, "%smout := make(map[string]%s, len(obj))\n", prefix, f.TypeName)
		fmt.Fprintf(b, "%sfor k, el := range obj {\n", prefix)
		fmt.Fprintf(b, "%s\titem, err := decode%sJSON(el)\n", prefix, f.TypeName)
		fmt.Fprintf(b, "%s\tif err != nil {\n%s\t\t%serr\n%s\t}\n", prefix, prefix, ret, prefix)
		fmt.Fprintf(b, "%s\tmout[k] = item\n", prefix)
		fmt.Fprintf(b, "%s}\n", prefix)
		fmt.Fprintf(b, "%s%s = mout\n", prefix, dest)
	default:
		// map[string]int etc. via encoding/json into temp — still not reflecting app structs
		fmt.Fprintf(b, "%svar mv %s\n", prefix, f.GoType())
		fmt.Fprintf(b, "%sif err := json.Unmarshal(%s, &mv); err != nil {\n", prefix, rawVar)
		fmt.Fprintf(b, "%s\t%shttpbinder.BindError(%q, \"payload\", \"invalid map\")\n", prefix, ret, f.Wire)
		fmt.Fprintf(b, "%s}\n", prefix)
		fmt.Fprintf(b, "%s%s = mv\n", prefix, dest)
	}
}

func emitEncode(b *bytes.Buffer, t TypePlan, types map[string]TypePlan) {
	fmt.Fprintf(b, "func encode%sMap(v %s) map[string]any {\n", t.Name, t.Name)
	b.WriteString("\tbody := map[string]any{}\n")
	for _, f := range t.Fields {
		if f.IsRest() {
			fmt.Fprintf(b, "\tfor k, val := range v.%s {\n", f.Name)
			b.WriteString("\t\tbody[k] = val\n")
			b.WriteString("\t}\n")
			continue
		}
		key := f.JSON
		if key == "" {
			key = f.Wire
		}
		switch f.Kind {
		case KindStruct:
			fmt.Fprintf(b, "\tbody[%q] = encode%sMap(v.%s)\n", key, f.TypeName, f.Name)
		case KindSlice:
			if f.ElemKind == KindStruct {
				fmt.Fprintf(b, "\t{\n")
				fmt.Fprintf(b, "\t\tarr := make([]any, len(v.%s))\n", f.Name)
				fmt.Fprintf(b, "\t\tfor i := range v.%s {\n", f.Name)
				fmt.Fprintf(b, "\t\t\tarr[i] = encode%sMap(v.%s[i])\n", f.TypeName, f.Name)
				fmt.Fprintf(b, "\t\t}\n")
				fmt.Fprintf(b, "\t\tbody[%q] = arr\n", key)
				fmt.Fprintf(b, "\t}\n")
			} else {
				fmt.Fprintf(b, "\tbody[%q] = v.%s\n", key, f.Name)
			}
		case KindMap:
			if f.ElemKind == KindStruct {
				fmt.Fprintf(b, "\t{\n")
				fmt.Fprintf(b, "\t\tm := make(map[string]any, len(v.%s))\n", f.Name)
				fmt.Fprintf(b, "\t\tfor k, item := range v.%s {\n", f.Name)
				fmt.Fprintf(b, "\t\t\tm[k] = encode%sMap(item)\n", f.TypeName)
				fmt.Fprintf(b, "\t\t}\n")
				fmt.Fprintf(b, "\t\tbody[%q] = m\n", key)
				fmt.Fprintf(b, "\t}\n")
			} else {
				fmt.Fprintf(b, "\tbody[%q] = v.%s\n", key, f.Name)
			}
		case "file":
			fmt.Fprintf(b, "\tbody[%q] = v.%s\n", key, f.Name)
		default:
			fmt.Fprintf(b, "\tbody[%q] = v.%s\n", key, f.Name)
		}
	}
	b.WriteString("\treturn body\n}\n\n")

	fmt.Fprintf(b, "func encode%s(w io.Writer, v %s) error {\n", t.Name, t.Name)
	fmt.Fprintf(b, "\treturn json.NewEncoder(w).Encode(encode%sMap(v))\n}\n\n", t.Name)
	_ = types
}

func emitBinder(b *bytes.Buffer, t TypePlan, types map[string]TypePlan) {
	fmt.Fprintf(b, "func bind%s(r *http.Request) (%s, error) {\n", t.Name, t.Name)
	fmt.Fprintf(b, "\tvar out %s\n", t.Name)

	hasChecks := false
	for _, f := range t.Fields {
		if f.Check.NeedsPresence() {
			hasChecks = true
			fmt.Fprintf(b, "\tvar present%s bool\n", f.Name)
		}
	}

	needsBody := false
	needsFiles := false
	needsForm := false // formBody used for scalar/rest fields
	for _, f := range t.Fields {
		if f.Source == SourceInput || f.Source == SourcePayload {
			needsBody = true
			if f.Kind == "file" {
				needsFiles = true
			} else if f.IsRest() || !f.IsComposite() {
				needsForm = true
			}
		}
	}
	if needsBody {
		b.WriteString("\tvar jsonBody map[string]jsonRaw\n")
		if needsForm || needsFiles {
			b.WriteString("\tvar formBody map[string]string\n")
		}
		if needsFiles {
			b.WriteString("\tvar fileBody map[string]httpbinder.File\n")
		}
		b.WriteString("\tvar bodyRead bool\n")
		b.WriteString("\treadBody := func() error {\n")
		b.WriteString("\t\tif bodyRead {\n\t\t\treturn nil\n\t\t}\n")
		b.WriteString("\t\tbodyRead = true\n")
		b.WriteString("\t\tif httpbinder.IsJSONRequest(r) {\n")
		b.WriteString("\t\t\tm, err := httpbinder.ReadJSONMap(r)\n")
		b.WriteString("\t\t\tif err != nil {\n\t\t\t\treturn err\n\t\t\t}\n")
		b.WriteString("\t\t\tjsonBody = m\n")
		b.WriteString("\t\t\treturn nil\n")
		b.WriteString("\t\t}\n")
		if needsForm || needsFiles {
			b.WriteString("\t\tif httpbinder.IsFormRequest(r) {\n")
			b.WriteString("\t\t\tm, err := httpbinder.ParseFormMap(r)\n")
			b.WriteString("\t\t\tif err != nil {\n\t\t\t\treturn err\n\t\t\t}\n")
			b.WriteString("\t\t\tformBody = m\n")
			b.WriteString("\t\t\treturn nil\n")
			b.WriteString("\t\t}\n")
			b.WriteString("\t\tif httpbinder.IsMultipartRequest(r) {\n")
			if needsFiles {
				b.WriteString("\t\t\tm, files, err := httpbinder.ParseMultipartMap(r)\n")
				b.WriteString("\t\t\tif err != nil {\n\t\t\t\treturn err\n\t\t\t}\n")
				b.WriteString("\t\t\tformBody = m\n")
				b.WriteString("\t\t\tfileBody = files\n")
			} else {
				b.WriteString("\t\t\tm, _, err := httpbinder.ParseMultipartMap(r)\n")
				b.WriteString("\t\t\tif err != nil {\n\t\t\t\treturn err\n\t\t\t}\n")
				b.WriteString("\t\t\tformBody = m\n")
			}
			b.WriteString("\t\t\treturn nil\n")
			b.WriteString("\t\t}\n")
		}
		b.WriteString("\t\treturn nil\n")
		b.WriteString("\t}\n")
	}

	for _, f := range t.Fields {
		if f.IsRest() {
			continue
		}
		emitFieldBind(b, f, types)
	}
	for _, f := range t.Fields {
		if f.IsRest() {
			emitRestField(b, t, f)
		}
	}

	if hasChecks {
		emitValidate(b, t)
		emitDefaults(b, t)
	}
	b.WriteString("\treturn out, nil\n}\n\n")
}

func bodyWireExclude(t TypePlan) []string {
	var out []string
	for _, f := range t.Fields {
		if f.IsRest() {
			continue
		}
		if f.Source == SourcePayload || f.Source == SourceInput {
			if f.Wire != "" && f.Wire != "*" {
				out = append(out, f.Wire)
			}
		}
	}
	return out
}

func emitRestField(b *bytes.Buffer, t TypePlan, f FieldPlan) {
	exclude := bodyWireExclude(t)
	b.WriteString("\tif err := readBody(); err != nil {\n\t\treturn out, err\n\t}\n")
	fmt.Fprintf(b, "\tif jsonBody != nil {\n")
	switch f.Kind {
	case KindRestAny:
		fmt.Fprintf(b, "\t\tm, err := httpbinder.RestJSONAny(jsonBody, []string{%s})\n", quoteStringList(exclude))
		b.WriteString("\t\tif err != nil {\n\t\t\treturn out, err\n\t\t}\n")
		fmt.Fprintf(b, "\t\tout.%s = m\n", f.Name)
	case KindRestRaw:
		fmt.Fprintf(b, "\t\tout.%s = httpbinder.RestJSONRaw(jsonBody, []string{%s})\n", f.Name, quoteStringList(exclude))
	}
	fmt.Fprintf(b, "\t} else if formBody != nil {\n")
	switch f.Kind {
	case KindRestAny:
		fmt.Fprintf(b, "\t\tout.%s = httpbinder.RestFormAny(formBody, []string{%s})\n", f.Name, quoteStringList(exclude))
	case KindRestRaw:
		fmt.Fprintf(b, "\t\tout.%s = httpbinder.RestFormRaw(formBody, []string{%s})\n", f.Name, quoteStringList(exclude))
	}
	fmt.Fprintf(b, "\t} else {\n")
	switch f.Kind {
	case KindRestAny:
		fmt.Fprintf(b, "\t\tout.%s = map[string]any{}\n", f.Name)
	case KindRestRaw:
		fmt.Fprintf(b, "\t\tout.%s = map[string]json.RawMessage{}\n", f.Name)
	}
	b.WriteString("\t}\n")
}

func quoteStringList(ss []string) string {
	if len(ss) == 0 {
		return ""
	}
	var b strings.Builder
	for i, s := range ss {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(strconv.Quote(s))
	}
	return b.String()
}

func emitFieldBind(b *bytes.Buffer, f FieldPlan, types map[string]TypePlan) {
	track := f.Check.NeedsPresence()
	switch f.Source {
	case SourcePath:
		if f.Kind == "string" {
			fmt.Fprintf(b, "\tout.%s = httpbinder.PathValue(r, %q)\n", f.Name, f.Wire)
			if track {
				fmt.Fprintf(b, "\tif out.%s != \"\" {\n\t\tpresent%s = true\n\t}\n", f.Name, f.Name)
			}
		} else if !f.IsComposite() && f.Kind != "file" {
			fmt.Fprintf(b, "\tif pv := httpbinder.PathValue(r, %q); pv != \"\" {\n", f.Wire)
			if track {
				fmt.Fprintf(b, "\t\tpresent%s = true\n", f.Name)
			}
			emitConvertFromStringIndented(b, f, "pv", "path", "\t\t")
			b.WriteString("\t}\n")
		}
	case SourceHeader:
		if f.Kind == "string" {
			fmt.Fprintf(b, "\tout.%s = httpbinder.HeaderValue(r, %q)\n", f.Name, f.Wire)
			if track {
				fmt.Fprintf(b, "\tif out.%s != \"\" {\n\t\tpresent%s = true\n\t}\n", f.Name, f.Name)
			}
		} else if !f.IsComposite() && f.Kind != "file" {
			fmt.Fprintf(b, "\tif hv := httpbinder.HeaderValue(r, %q); hv != \"\" {\n", f.Wire)
			if track {
				fmt.Fprintf(b, "\t\tpresent%s = true\n", f.Name)
			}
			emitConvertFromStringIndented(b, f, "hv", "header", "\t\t")
			b.WriteString("\t}\n")
		}
	case SourceCookie:
		if !f.IsComposite() {
			fmt.Fprintf(b, "\tif cv, ok := httpbinder.CookieValue(r, %q); ok {\n", f.Wire)
			if track {
				fmt.Fprintf(b, "\t\tpresent%s = true\n", f.Name)
			}
			emitConvertFromStringIndented(b, f, "cv", "cookie", "\t\t")
			b.WriteString("\t}\n")
		}
	case SourceMethod:
		if f.Kind == "string" {
			fmt.Fprintf(b, "\tout.%s = r.Method\n", f.Name)
			if track {
				fmt.Fprintf(b, "\tpresent%s = true\n", f.Name)
			}
		}
	case SourceQuery:
		if !f.IsComposite() {
			fmt.Fprintf(b, "\tif qv, ok := httpbinder.QueryValue(r, %q); ok {\n", f.Wire)
			if track {
				fmt.Fprintf(b, "\t\tpresent%s = true\n", f.Name)
			}
			emitConvertFromStringIndented(b, f, "qv", "query", "\t\t")
			b.WriteString("\t}\n")
		}
	case SourcePayload:
		emitPayloadField(b, f, types, "\t", track)
	case SourceInput:
		if f.IsComposite() {
			// Nested only from body for input-tagged composites.
			emitPayloadField(b, f, types, "\t", track)
			return
		}
		fmt.Fprintf(b, "\tif qv, ok := httpbinder.QueryValue(r, %q); ok {\n", f.Wire)
		if track {
			fmt.Fprintf(b, "\t\tpresent%s = true\n", f.Name)
		}
		emitConvertFromStringIndented(b, f, "qv", "query", "\t\t")
		b.WriteString("\t} else {\n")
		emitPayloadField(b, f, types, "\t\t", track)
		b.WriteString("\t}\n")
	}
}

func emitPayloadField(b *bytes.Buffer, f FieldPlan, types map[string]TypePlan, prefix string, track bool) {
	fmt.Fprintf(b, "%sif err := readBody(); err != nil {\n%s\treturn out, err\n%s}\n", prefix, prefix, prefix)
	if f.Kind == "file" {
		fmt.Fprintf(b, "%sif fv, ok := fileBody[%q]; ok {\n", prefix, f.Wire)
		if track {
			fmt.Fprintf(b, "%s\tpresent%s = true\n", prefix, f.Name)
		}
		fmt.Fprintf(b, "%s\tout.%s = fv\n", prefix, f.Name)
		fmt.Fprintf(b, "%s} else if fileBody != nil {\n", prefix)
		fmt.Fprintf(b, "%s\treturn out, httpbinder.BindError(%q, \"payload\", \"missing file\")\n", prefix, f.Wire)
		fmt.Fprintf(b, "%s}\n", prefix)
		return
	}
	// JSON path (including nested)
	fmt.Fprintf(b, "%sif raw, ok := jsonBody[%q]; ok {\n", prefix, f.Wire)
	if track {
		fmt.Fprintf(b, "%s\tpresent%s = true\n", prefix, f.Name)
	}
	emitAssignFromRaw(b, f, types, "raw", prefix+"\t", "out."+f.Name, true)
	if f.IsComposite() {
		fmt.Fprintf(b, "%s}\n", prefix)
		return
	}
	// form only for scalars
	fmt.Fprintf(b, "%s} else if formBody != nil {\n", prefix)
	fmt.Fprintf(b, "%s\tif fv, ok := formBody[%q]; ok {\n", prefix, f.Wire)
	if track {
		fmt.Fprintf(b, "%s\t\tpresent%s = true\n", prefix, f.Name)
	}
	emitConvertFromStringIndented(b, f, "fv", "payload", prefix+"\t\t")
	fmt.Fprintf(b, "%s\t}\n", prefix)
	fmt.Fprintf(b, "%s}\n", prefix)
}

func emitConvertFromStringIndented(b *bytes.Buffer, f FieldPlan, varName, location, prefix string) {
	switch f.Kind {
	case "int":
		fmt.Fprintf(b, "%sv, err := httpbinder.ParseInt(%s)\n", prefix, varName)
		fmt.Fprintf(b, "%sif err != nil {\n%s\treturn out, httpbinder.BindError(%q, %q, \"invalid int\")\n%s}\n", prefix, prefix, f.Wire, location, prefix)
		fmt.Fprintf(b, "%sout.%s = v\n", prefix, f.Name)
	case "int64":
		fmt.Fprintf(b, "%sv, err := httpbinder.ParseInt64(%s)\n", prefix, varName)
		fmt.Fprintf(b, "%sif err != nil {\n%s\treturn out, httpbinder.BindError(%q, %q, \"invalid int64\")\n%s}\n", prefix, prefix, f.Wire, location, prefix)
		fmt.Fprintf(b, "%sout.%s = v\n", prefix, f.Name)
	case "bool":
		fmt.Fprintf(b, "%sv, err := httpbinder.ParseBool(%s)\n", prefix, varName)
		fmt.Fprintf(b, "%sif err != nil {\n%s\treturn out, httpbinder.BindError(%q, %q, \"invalid bool\")\n%s}\n", prefix, prefix, f.Wire, location, prefix)
		fmt.Fprintf(b, "%sout.%s = v\n", prefix, f.Name)
	case "float64":
		fmt.Fprintf(b, "%sv, err := httpbinder.ParseFloat64(%s)\n", prefix, varName)
		fmt.Fprintf(b, "%sif err != nil {\n%s\treturn out, httpbinder.BindError(%q, %q, \"invalid float64\")\n%s}\n", prefix, prefix, f.Wire, location, prefix)
		fmt.Fprintf(b, "%sout.%s = v\n", prefix, f.Name)
	case "string":
		fmt.Fprintf(b, "%sout.%s = %s\n", prefix, f.Name, varName)
	}
}

func emitValidate(b *bytes.Buffer, t TypePlan) {
	b.WriteString("\tvar checkFields []httpbinder.FieldError\n")
	for _, f := range t.Fields {
		if !f.Check.HasRules() {
			continue
		}
		loc := checkLocation(f.Source)
		c := f.Check
		if c.Required {
			switch f.Kind {
			case "string":
				fmt.Fprintf(b, "\tif !present%s || out.%s == \"\" {\n", f.Name, f.Name)
			case "file":
				fmt.Fprintf(b, "\tif !present%s || out.%s.Empty() {\n", f.Name, f.Name)
			default:
				fmt.Fprintf(b, "\tif !present%s {\n", f.Name)
			}
			fmt.Fprintf(b, "\t\tcheckFields = append(checkFields, httpbinder.Field(%q, %q, \"required\"))\n", f.Wire, loc)
			b.WriteString("\t}\n")
		}

		hasValueConstraints := c.Min != nil || c.Max != nil ||
			c.MinLen != nil || c.MaxLen != nil || c.Len != nil ||
			len(c.Enum) > 0 || c.Email || c.UUID || c.Date || c.Time || c.DateTime || c.Pattern != ""
		if hasValueConstraints {
			fmt.Fprintf(b, "\tif present%s {\n", f.Name)
			if c.Min != nil {
				switch f.Kind {
				case "int":
					fmt.Fprintf(b, "\t\tif out.%s < %s {\n", f.Name, intLit(*c.Min))
				case "int64":
					fmt.Fprintf(b, "\t\tif out.%s < %s {\n", f.Name, int64Lit(*c.Min))
				case "float64":
					fmt.Fprintf(b, "\t\tif out.%s < %s {\n", f.Name, floatLit(*c.Min))
				}
				fmt.Fprintf(b, "\t\t\tcheckFields = append(checkFields, httpbinder.Field(%q, %q, %q))\n", f.Wire, loc, fmt.Sprintf("must be >= %v", numMsg(*c.Min)))
				b.WriteString("\t\t}\n")
			}
			if c.Max != nil {
				switch f.Kind {
				case "int":
					fmt.Fprintf(b, "\t\tif out.%s > %s {\n", f.Name, intLit(*c.Max))
				case "int64":
					fmt.Fprintf(b, "\t\tif out.%s > %s {\n", f.Name, int64Lit(*c.Max))
				case "float64":
					fmt.Fprintf(b, "\t\tif out.%s > %s {\n", f.Name, floatLit(*c.Max))
				}
				fmt.Fprintf(b, "\t\t\tcheckFields = append(checkFields, httpbinder.Field(%q, %q, %q))\n", f.Wire, loc, fmt.Sprintf("must be <= %v", numMsg(*c.Max)))
				b.WriteString("\t\t}\n")
			}
			if f.Kind == "string" {
				if c.MinLen != nil {
					fmt.Fprintf(b, "\t\tif len(out.%s) < %d {\n", f.Name, *c.MinLen)
					fmt.Fprintf(b, "\t\t\tcheckFields = append(checkFields, httpbinder.Field(%q, %q, %q))\n", f.Wire, loc, fmt.Sprintf("length must be >= %d", *c.MinLen))
					b.WriteString("\t\t}\n")
				}
				if c.MaxLen != nil {
					fmt.Fprintf(b, "\t\tif len(out.%s) > %d {\n", f.Name, *c.MaxLen)
					fmt.Fprintf(b, "\t\t\tcheckFields = append(checkFields, httpbinder.Field(%q, %q, %q))\n", f.Wire, loc, fmt.Sprintf("length must be <= %d", *c.MaxLen))
					b.WriteString("\t\t}\n")
				}
				if c.Len != nil {
					fmt.Fprintf(b, "\t\tif len(out.%s) != %d {\n", f.Name, *c.Len)
					fmt.Fprintf(b, "\t\t\tcheckFields = append(checkFields, httpbinder.Field(%q, %q, %q))\n", f.Wire, loc, fmt.Sprintf("length must be %d", *c.Len))
					b.WriteString("\t\t}\n")
				}
			}
			if len(c.Enum) > 0 {
				b.WriteString("\t\t{\n")
				b.WriteString("\t\t\tenumOK := false\n")
				for _, v := range c.Enum {
					lit, _ := defaultGoLiteral(f.Kind, v)
					fmt.Fprintf(b, "\t\t\tif out.%s == %s {\n\t\t\t\tenumOK = true\n\t\t\t}\n", f.Name, lit)
				}
				b.WriteString("\t\t\tif !enumOK {\n")
				msg := "must be one of: " + joinEnumMsg(c.Enum)
				fmt.Fprintf(b, "\t\t\t\tcheckFields = append(checkFields, httpbinder.Field(%q, %q, %q))\n", f.Wire, loc, msg)
				b.WriteString("\t\t\t}\n")
				b.WriteString("\t\t}\n")
			}
			if f.Kind == "string" && (c.Email || c.UUID || c.Date || c.Time || c.DateTime || c.Pattern != "") {
				fmt.Fprintf(b, "\t\tif out.%s != \"\" {\n", f.Name)
				if c.Email {
					fmt.Fprintf(b, "\t\t\tif !httpbinder.CheckEmail(out.%s) {\n", f.Name)
					fmt.Fprintf(b, "\t\t\t\tcheckFields = append(checkFields, httpbinder.Field(%q, %q, \"must be a valid email\"))\n", f.Wire, loc)
					b.WriteString("\t\t\t}\n")
				}
				if c.UUID {
					fmt.Fprintf(b, "\t\t\tif !httpbinder.CheckUUID(out.%s) {\n", f.Name)
					fmt.Fprintf(b, "\t\t\t\tcheckFields = append(checkFields, httpbinder.Field(%q, %q, \"must be a valid uuid\"))\n", f.Wire, loc)
					b.WriteString("\t\t\t}\n")
				}
				if c.Date {
					fmt.Fprintf(b, "\t\t\tif !httpbinder.CheckDate(out.%s) {\n", f.Name)
					fmt.Fprintf(b, "\t\t\t\tcheckFields = append(checkFields, httpbinder.Field(%q, %q, \"must be ISO date\"))\n", f.Wire, loc)
					b.WriteString("\t\t\t}\n")
				}
				if c.Time {
					fmt.Fprintf(b, "\t\t\tif !httpbinder.CheckTime(out.%s) {\n", f.Name)
					fmt.Fprintf(b, "\t\t\t\tcheckFields = append(checkFields, httpbinder.Field(%q, %q, \"must be ISO time\"))\n", f.Wire, loc)
					b.WriteString("\t\t\t}\n")
				}
				if c.DateTime {
					fmt.Fprintf(b, "\t\t\tif !httpbinder.CheckDateTime(out.%s) {\n", f.Name)
					fmt.Fprintf(b, "\t\t\t\tcheckFields = append(checkFields, httpbinder.Field(%q, %q, \"must be RFC3339 datetime\"))\n", f.Wire, loc)
					b.WriteString("\t\t\t}\n")
				}
				if c.Pattern != "" {
					fmt.Fprintf(b, "\t\t\tif !checkPattern%s%s.MatchString(out.%s) {\n", t.Name, f.Name, f.Name)
					fmt.Fprintf(b, "\t\t\t\tcheckFields = append(checkFields, httpbinder.Field(%q, %q, \"must match pattern\"))\n", f.Wire, loc)
					b.WriteString("\t\t\t}\n")
				}
				b.WriteString("\t\t}\n")
			}
			b.WriteString("\t}\n")
		}
	}
	b.WriteString("\tif len(checkFields) > 0 {\n")
	b.WriteString("\t\treturn out, httpbinder.Validation(checkFields...)\n")
	b.WriteString("\t}\n")
}

func emitDefaults(b *bytes.Buffer, t TypePlan) {
	for _, f := range t.Fields {
		if !f.Check.HasDefault {
			continue
		}
		lit, err := defaultGoLiteral(f.Kind, f.Check.Default)
		if err != nil {
			continue
		}
		fmt.Fprintf(b, "\tif !present%s {\n", f.Name)
		fmt.Fprintf(b, "\t\tout.%s = %s\n", f.Name, lit)
		b.WriteString("\t}\n")
	}
}

func joinEnumMsg(vals []string) string {
	return joinComma(vals)
}

func joinComma(vals []string) string {
	if len(vals) == 0 {
		return ""
	}
	out := vals[0]
	for i := 1; i < len(vals); i++ {
		out += ", " + vals[i]
	}
	return out
}

func intLit(f float64) string {
	return strconv.FormatInt(int64(f), 10)
}

func int64Lit(f float64) string {
	return fmt.Sprintf("int64(%d)", int64(f))
}

func floatLit(f float64) string {
	return strconv.FormatFloat(f, 'g', -1, 64)
}

func numMsg(f float64) any {
	if f == float64(int64(f)) {
		return int64(f)
	}
	return f
}

func emitWriter(b *bytes.Buffer, t TypePlan, types map[string]TypePlan) {
	fmt.Fprintf(b, "func write%s(w http.ResponseWriter, r *http.Request, v %s) error {\n", t.Name, t.Name)
	b.WriteString("\t_ = r\n")
	fmt.Fprintf(b, "\treturn httpbinder.WriteJSON(w, http.StatusOK, encode%sMap(v))\n", t.Name)
	b.WriteString("}\n\n")
	_ = types
}
