package generator

import (
	"bytes"
	"fmt"
	"go/format"
)

// Emit generates Go source for type-specific binders and writers.
// The output does not import "reflect".
func Emit(plan *PackagePlan) ([]byte, error) {
	if plan == nil {
		return nil, fmt.Errorf("nil plan")
	}
	var b bytes.Buffer
	b.WriteString("// Code generated by httpbinder; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", plan.Package)
	b.WriteString("import (\n")
	b.WriteString("\t\"encoding/json\"\n")
	b.WriteString("\t\"net/http\"\n\n")
	b.WriteString("\t\"github.com/shibukawayoshiki/httpbind-go\"\n")
	b.WriteString(")\n\n")
	b.WriteString("type jsonRaw = json.RawMessage\n\n")

	b.WriteString("func init() {\n")
	for _, t := range plan.Types {
		fmt.Fprintf(&b, "\thttpbinder.RegisterBind[%s](bind%s)\n", t.Name, t.Name)
		fmt.Fprintf(&b, "\thttpbinder.RegisterWrite[%s](write%s)\n", t.Name, t.Name)
	}
	b.WriteString("}\n\n")

	for _, t := range plan.Types {
		emitBinder(&b, t)
		emitWriter(&b, t)
	}

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return b.Bytes(), fmt.Errorf("format generated code: %w\n%s", err, b.String())
	}
	return formatted, nil
}

func emitBinder(b *bytes.Buffer, t TypePlan) {
	fmt.Fprintf(b, "func bind%s(r *http.Request) (%s, error) {\n", t.Name, t.Name)
	fmt.Fprintf(b, "\tvar out %s\n", t.Name)

	needsBody := false
	for _, f := range t.Fields {
		if f.Source == SourceInput || f.Source == SourcePayload {
			needsBody = true
			break
		}
	}
	if needsBody {
		b.WriteString("\tvar jsonBody map[string]jsonRaw\n")
		b.WriteString("\tvar formBody map[string]string\n")
		b.WriteString("\tvar bodyRead bool\n")
		b.WriteString("\treadBody := func() error {\n")
		b.WriteString("\t\tif bodyRead {\n\t\t\treturn nil\n\t\t}\n")
		b.WriteString("\t\tbodyRead = true\n")
		b.WriteString("\t\tif httpbinder.IsJSONRequest(r) {\n")
		b.WriteString("\t\t\tm, err := httpbinder.ReadJSONMap(r)\n")
		b.WriteString("\t\t\tif err != nil {\n\t\t\t\treturn err\n\t\t\t}\n")
		b.WriteString("\t\t\tjsonBody = m\n")
		b.WriteString("\t\t\treturn nil\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t\tif httpbinder.IsFormRequest(r) {\n")
		b.WriteString("\t\t\tm, err := httpbinder.ParseFormMap(r)\n")
		b.WriteString("\t\t\tif err != nil {\n\t\t\t\treturn err\n\t\t\t}\n")
		b.WriteString("\t\t\tformBody = m\n")
		b.WriteString("\t\t\treturn nil\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t\treturn nil\n")
		b.WriteString("\t}\n")
	}

	for _, f := range t.Fields {
		emitFieldBind(b, f)
	}
	b.WriteString("\treturn out, nil\n}\n\n")
}

func emitFieldBind(b *bytes.Buffer, f FieldPlan) {
	switch f.Source {
	case SourcePath:
		if f.Kind == "string" {
			fmt.Fprintf(b, "\tout.%s = httpbinder.PathValue(r, %q)\n", f.Name, f.Wire)
		} else {
			fmt.Fprintf(b, "\tif pv := httpbinder.PathValue(r, %q); pv != \"\" {\n", f.Wire)
			emitConvertFromStringIndented(b, f, "pv", "path", "\t\t")
			b.WriteString("\t}\n")
		}
	case SourceHeader:
		if f.Kind == "string" {
			fmt.Fprintf(b, "\tout.%s = httpbinder.HeaderValue(r, %q)\n", f.Name, f.Wire)
		} else {
			fmt.Fprintf(b, "\tif hv := httpbinder.HeaderValue(r, %q); hv != \"\" {\n", f.Wire)
			emitConvertFromStringIndented(b, f, "hv", "header", "\t\t")
			b.WriteString("\t}\n")
		}
	case SourceCookie:
		fmt.Fprintf(b, "\tif cv, ok := httpbinder.CookieValue(r, %q); ok {\n", f.Wire)
		emitConvertFromStringIndented(b, f, "cv", "cookie", "\t\t")
		b.WriteString("\t}\n")
	case SourceMethod:
		if f.Kind == "string" {
			fmt.Fprintf(b, "\tout.%s = r.Method\n", f.Name)
		}
	case SourceQuery:
		fmt.Fprintf(b, "\tif qv, ok := httpbinder.QueryValue(r, %q); ok {\n", f.Wire)
		emitConvertFromStringIndented(b, f, "qv", "query", "\t\t")
		b.WriteString("\t}\n")
	case SourcePayload:
		emitPayloadField(b, f, "\t")
	case SourceInput:
		fmt.Fprintf(b, "\tif qv, ok := httpbinder.QueryValue(r, %q); ok {\n", f.Wire)
		emitConvertFromStringIndented(b, f, "qv", "query", "\t\t")
		b.WriteString("\t} else {\n")
		emitPayloadField(b, f, "\t\t")
		b.WriteString("\t}\n")
	}
}

func emitPayloadField(b *bytes.Buffer, f FieldPlan, prefix string) {
	fmt.Fprintf(b, "%sif err := readBody(); err != nil {\n%s\treturn out, err\n%s}\n", prefix, prefix, prefix)
	fmt.Fprintf(b, "%sif raw, ok := jsonBody[%q]; ok {\n", prefix, f.Wire)
	switch f.Kind {
	case "string":
		fmt.Fprintf(b, "%s\tv, err := httpbinder.DecodeJSONString(raw)\n", prefix)
		fmt.Fprintf(b, "%s\tif err != nil {\n%s\t\treturn out, httpbinder.BindError(%q, \"payload\", \"invalid string\")\n%s\t}\n", prefix, prefix, f.Wire, prefix)
		fmt.Fprintf(b, "%s\tout.%s = v\n", prefix, f.Name)
	case "int":
		fmt.Fprintf(b, "%s\tv, err := httpbinder.DecodeJSONInt(raw)\n", prefix)
		fmt.Fprintf(b, "%s\tif err != nil {\n%s\t\treturn out, httpbinder.BindError(%q, \"payload\", \"invalid int\")\n%s\t}\n", prefix, prefix, f.Wire, prefix)
		fmt.Fprintf(b, "%s\tout.%s = v\n", prefix, f.Name)
	case "int64":
		fmt.Fprintf(b, "%s\tv, err := httpbinder.DecodeJSONInt64(raw)\n", prefix)
		fmt.Fprintf(b, "%s\tif err != nil {\n%s\t\treturn out, httpbinder.BindError(%q, \"payload\", \"invalid int64\")\n%s\t}\n", prefix, prefix, f.Wire, prefix)
		fmt.Fprintf(b, "%s\tout.%s = v\n", prefix, f.Name)
	case "bool":
		fmt.Fprintf(b, "%s\tv, err := httpbinder.DecodeJSONBool(raw)\n", prefix)
		fmt.Fprintf(b, "%s\tif err != nil {\n%s\t\treturn out, httpbinder.BindError(%q, \"payload\", \"invalid bool\")\n%s\t}\n", prefix, prefix, f.Wire, prefix)
		fmt.Fprintf(b, "%s\tout.%s = v\n", prefix, f.Name)
	case "float64":
		fmt.Fprintf(b, "%s\tv, err := httpbinder.DecodeJSONFloat64(raw)\n", prefix)
		fmt.Fprintf(b, "%s\tif err != nil {\n%s\t\treturn out, httpbinder.BindError(%q, \"payload\", \"invalid float64\")\n%s\t}\n", prefix, prefix, f.Wire, prefix)
		fmt.Fprintf(b, "%s\tout.%s = v\n", prefix, f.Name)
	}
	fmt.Fprintf(b, "%s} else if formBody != nil {\n", prefix)
	fmt.Fprintf(b, "%s\tif fv, ok := formBody[%q]; ok {\n", prefix, f.Wire)
	emitConvertFromStringIndented(b, f, "fv", "payload", prefix+"\t\t")
	fmt.Fprintf(b, "%s\t}\n", prefix)
	fmt.Fprintf(b, "%s}\n", prefix)
}

func emitConvertFromStringIndented(b *bytes.Buffer, f FieldPlan, varName, location, prefix string) {
	switch f.Kind {
	case "int":
		fmt.Fprintf(b, "%sv, err := httpbinder.ParseInt(%s)\n", prefix, varName)
		fmt.Fprintf(b, "%sif err != nil {\n%s\treturn out, httpbinder.BindError(%q, %q, \"invalid int\")\n%s}\n", prefix, prefix, f.Wire, location, prefix)
		fmt.Fprintf(b, "%sout.%s = v\n", prefix, f.Name)
	case "int64":
		fmt.Fprintf(b, "%sv, err := httpbinder.ParseInt64(%s)\n", prefix, varName)
		fmt.Fprintf(b, "%sif err != nil {\n%s\treturn out, httpbinder.BindError(%q, %q, \"invalid int64\")\n%s}\n", prefix, prefix, f.Wire, location, prefix)
		fmt.Fprintf(b, "%sout.%s = v\n", prefix, f.Name)
	case "bool":
		fmt.Fprintf(b, "%sv, err := httpbinder.ParseBool(%s)\n", prefix, varName)
		fmt.Fprintf(b, "%sif err != nil {\n%s\treturn out, httpbinder.BindError(%q, %q, \"invalid bool\")\n%s}\n", prefix, prefix, f.Wire, location, prefix)
		fmt.Fprintf(b, "%sout.%s = v\n", prefix, f.Name)
	case "float64":
		fmt.Fprintf(b, "%sv, err := httpbinder.ParseFloat64(%s)\n", prefix, varName)
		fmt.Fprintf(b, "%sif err != nil {\n%s\treturn out, httpbinder.BindError(%q, %q, \"invalid float64\")\n%s}\n", prefix, prefix, f.Wire, location, prefix)
		fmt.Fprintf(b, "%sout.%s = v\n", prefix, f.Name)
	case "string":
		fmt.Fprintf(b, "%sout.%s = %s\n", prefix, f.Name, varName)
	}
}

func emitWriter(b *bytes.Buffer, t TypePlan) {
	fmt.Fprintf(b, "func write%s(w http.ResponseWriter, r *http.Request, v %s) error {\n", t.Name, t.Name)
	b.WriteString("\t_ = r\n")
	b.WriteString("\tbody := map[string]any{\n")
	for _, f := range t.Fields {
		fmt.Fprintf(b, "\t\t%q: v.%s,\n", f.JSON, f.Name)
	}
	b.WriteString("\t}\n")
	b.WriteString("\treturn httpbinder.WriteJSON(w, http.StatusOK, body)\n")
	b.WriteString("}\n\n")
}
