// Code generated by tinybind; DO NOT EDIT.

package mappingfixture

import (
	"encoding/json"
	"io"
	"net/http"

	"github.com/shibukawa/tinybind-go"
	"github.com/shibukawa/tinybind-go/jsonbind"
)

type jsonRaw = json.RawMessage

func init() {
	httpbind.RegisterBind[CreateUserRequest](bindCreateUserRequest)
	httpbind.RegisterWrite[CreateUserRequest](writeCreateUserRequest)
	jsonbind.RegisterDecode[CreateUserRequest](decodeCreateUserRequestBytes)
	jsonbind.RegisterEncode[CreateUserRequest](encodeCreateUserRequest)
	httpbind.RegisterBind[CreateUserResponse](bindCreateUserResponse)
	httpbind.RegisterWrite[CreateUserResponse](writeCreateUserResponse)
	jsonbind.RegisterDecode[CreateUserResponse](decodeCreateUserResponseBytes)
	jsonbind.RegisterEncode[CreateUserResponse](encodeCreateUserResponse)
	httpbind.RegisterBind[SearchRequest](bindSearchRequest)
	httpbind.RegisterWrite[SearchRequest](writeSearchRequest)
	jsonbind.RegisterDecode[SearchRequest](decodeSearchRequestBytes)
	jsonbind.RegisterEncode[SearchRequest](encodeSearchRequest)
	httpbind.RegisterBind[SearchResponse](bindSearchResponse)
	httpbind.RegisterWrite[SearchResponse](writeSearchResponse)
	jsonbind.RegisterDecode[SearchResponse](decodeSearchResponseBytes)
	jsonbind.RegisterEncode[SearchResponse](encodeSearchResponse)
	httpbind.RegisterBind[UploadAvatarRequest](bindUploadAvatarRequest)
	httpbind.RegisterWrite[UploadAvatarRequest](writeUploadAvatarRequest)
	jsonbind.RegisterDecode[UploadAvatarRequest](decodeUploadAvatarRequestBytes)
	jsonbind.RegisterEncode[UploadAvatarRequest](encodeUploadAvatarRequest)
	httpbind.RegisterBind[PatchWithExtrasRequest](bindPatchWithExtrasRequest)
	httpbind.RegisterWrite[PatchWithExtrasRequest](writePatchWithExtrasRequest)
	jsonbind.RegisterDecode[PatchWithExtrasRequest](decodePatchWithExtrasRequestBytes)
	jsonbind.RegisterEncode[PatchWithExtrasRequest](encodePatchWithExtrasRequest)
	httpbind.RegisterBind[PatchWithExtrasRawRequest](bindPatchWithExtrasRawRequest)
	httpbind.RegisterWrite[PatchWithExtrasRawRequest](writePatchWithExtrasRawRequest)
	jsonbind.RegisterDecode[PatchWithExtrasRawRequest](decodePatchWithExtrasRawRequestBytes)
	jsonbind.RegisterEncode[PatchWithExtrasRawRequest](encodePatchWithExtrasRawRequest)
	httpbind.RegisterBind[NestedCustomer](bindNestedCustomer)
	httpbind.RegisterWrite[NestedCustomer](writeNestedCustomer)
	jsonbind.RegisterDecode[NestedCustomer](decodeNestedCustomerBytes)
	jsonbind.RegisterEncode[NestedCustomer](encodeNestedCustomer)
	httpbind.RegisterBind[NestedLineItem](bindNestedLineItem)
	httpbind.RegisterWrite[NestedLineItem](writeNestedLineItem)
	jsonbind.RegisterDecode[NestedLineItem](decodeNestedLineItemBytes)
	jsonbind.RegisterEncode[NestedLineItem](encodeNestedLineItem)
	httpbind.RegisterBind[NestedOrderRequest](bindNestedOrderRequest)
	httpbind.RegisterWrite[NestedOrderRequest](writeNestedOrderRequest)
	jsonbind.RegisterDecode[NestedOrderRequest](decodeNestedOrderRequestBytes)
	jsonbind.RegisterEncode[NestedOrderRequest](encodeNestedOrderRequest)
	httpbind.RegisterBind[CodecOnlyNote](bindCodecOnlyNote)
	httpbind.RegisterWrite[CodecOnlyNote](writeCodecOnlyNote)
	jsonbind.RegisterDecode[CodecOnlyNote](decodeCodecOnlyNoteBytes)
	jsonbind.RegisterEncode[CodecOnlyNote](encodeCodecOnlyNote)
}

func decodeCreateUserRequestBytes(data []byte) (CreateUserRequest, error) {
	return decodeCreateUserRequestJSON(json.RawMessage(data))
}

func decodeCreateUserRequestJSON(raw json.RawMessage) (CreateUserRequest, error) {
	var out CreateUserRequest
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["name"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("name", "invalid string", err)
		}
		out.Name = v
	}
	if raw, ok := m["email"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("email", "invalid string", err)
		}
		out.Email = v
	}
	return out, nil
}

func encodeCreateUserRequestMap(v CreateUserRequest) map[string]any {
	body := map[string]any{}
	body["name"] = v.Name
	body["email"] = v.Email
	body["org_id"] = v.OrgID
	body["Authorization"] = v.Token
	return body
}

func encodeCreateUserRequest(w io.Writer, v CreateUserRequest) error {
	return json.NewEncoder(w).Encode(encodeCreateUserRequestMap(v))
}

func bindCreateUserRequest(r *http.Request) (CreateUserRequest, error) {
	var out CreateUserRequest
	var jsonBody map[string]jsonRaw
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbind.IsJSONRequest(r) {
			m, err := httpbind.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbind.IsFormRequest(r) {
			m, err := httpbind.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbind.IsMultipartRequest(r) {
			m, _, err := httpbind.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if qv, ok := httpbind.QueryValue(r, "name"); ok {
		out.Name = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["name"]; ok {
			v, err := jsonbind.DecodeJSONString(raw)
			if err != nil {
				return out, jsonbind.FieldError("name", "invalid string", err)
			}
			out.Name = v
		} else if formBody != nil {
			if fv, ok := formBody["name"]; ok {
				out.Name = fv
			}
		}
	}
	if qv, ok := httpbind.QueryValue(r, "email"); ok {
		out.Email = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["email"]; ok {
			v, err := jsonbind.DecodeJSONString(raw)
			if err != nil {
				return out, jsonbind.FieldError("email", "invalid string", err)
			}
			out.Email = v
		} else if formBody != nil {
			if fv, ok := formBody["email"]; ok {
				out.Email = fv
			}
		}
	}
	out.OrgID = httpbind.PathValue(r, "org_id")
	out.Token = httpbind.HeaderValue(r, "Authorization")
	return out, nil
}

func writeCreateUserRequest(w http.ResponseWriter, r *http.Request, v CreateUserRequest) error {
	_ = r
	return httpbind.WriteJSON(w, http.StatusOK, encodeCreateUserRequestMap(v))
}

func decodeCreateUserResponseBytes(data []byte) (CreateUserResponse, error) {
	return decodeCreateUserResponseJSON(json.RawMessage(data))
}

func decodeCreateUserResponseJSON(raw json.RawMessage) (CreateUserResponse, error) {
	var out CreateUserResponse
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["id"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("iD", "invalid string", err)
		}
		out.ID = v
	}
	if raw, ok := m["name"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("name", "invalid string", err)
		}
		out.Name = v
	}
	if raw, ok := m["email"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("email", "invalid string", err)
		}
		out.Email = v
	}
	return out, nil
}

func encodeCreateUserResponseMap(v CreateUserResponse) map[string]any {
	body := map[string]any{}
	body["id"] = v.ID
	body["name"] = v.Name
	body["email"] = v.Email
	return body
}

func encodeCreateUserResponse(w io.Writer, v CreateUserResponse) error {
	return json.NewEncoder(w).Encode(encodeCreateUserResponseMap(v))
}

func bindCreateUserResponse(r *http.Request) (CreateUserResponse, error) {
	var out CreateUserResponse
	var jsonBody map[string]jsonRaw
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbind.IsJSONRequest(r) {
			m, err := httpbind.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbind.IsFormRequest(r) {
			m, err := httpbind.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbind.IsMultipartRequest(r) {
			m, _, err := httpbind.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if qv, ok := httpbind.QueryValue(r, "iD"); ok {
		out.ID = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["iD"]; ok {
			v, err := jsonbind.DecodeJSONString(raw)
			if err != nil {
				return out, jsonbind.FieldError("iD", "invalid string", err)
			}
			out.ID = v
		} else if formBody != nil {
			if fv, ok := formBody["iD"]; ok {
				out.ID = fv
			}
		}
	}
	if qv, ok := httpbind.QueryValue(r, "name"); ok {
		out.Name = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["name"]; ok {
			v, err := jsonbind.DecodeJSONString(raw)
			if err != nil {
				return out, jsonbind.FieldError("name", "invalid string", err)
			}
			out.Name = v
		} else if formBody != nil {
			if fv, ok := formBody["name"]; ok {
				out.Name = fv
			}
		}
	}
	if qv, ok := httpbind.QueryValue(r, "email"); ok {
		out.Email = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["email"]; ok {
			v, err := jsonbind.DecodeJSONString(raw)
			if err != nil {
				return out, jsonbind.FieldError("email", "invalid string", err)
			}
			out.Email = v
		} else if formBody != nil {
			if fv, ok := formBody["email"]; ok {
				out.Email = fv
			}
		}
	}
	return out, nil
}

func writeCreateUserResponse(w http.ResponseWriter, r *http.Request, v CreateUserResponse) error {
	_ = r
	return httpbind.WriteJSON(w, http.StatusOK, encodeCreateUserResponseMap(v))
}

func decodeSearchRequestBytes(data []byte) (SearchRequest, error) {
	return decodeSearchRequestJSON(json.RawMessage(data))
}

func decodeSearchRequestJSON(raw json.RawMessage) (SearchRequest, error) {
	var out SearchRequest
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["filter"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("filter", "invalid string", err)
		}
		out.Filter = v
	}
	return out, nil
}

func encodeSearchRequestMap(v SearchRequest) map[string]any {
	body := map[string]any{}
	body["keyword"] = v.Keyword
	body["page"] = v.Page
	body["filter"] = v.Filter
	return body
}

func encodeSearchRequest(w io.Writer, v SearchRequest) error {
	return json.NewEncoder(w).Encode(encodeSearchRequestMap(v))
}

func bindSearchRequest(r *http.Request) (SearchRequest, error) {
	var out SearchRequest
	var jsonBody map[string]jsonRaw
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbind.IsJSONRequest(r) {
			m, err := httpbind.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbind.IsFormRequest(r) {
			m, err := httpbind.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbind.IsMultipartRequest(r) {
			m, _, err := httpbind.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if qv, ok := httpbind.QueryValue(r, "keyword"); ok {
		out.Keyword = qv
	}
	if qv, ok := httpbind.QueryValue(r, "page"); ok {
		v, err := httpbind.ParseInt(qv)
		if err != nil {
			return out, httpbind.BindError("page", "query", "invalid int")
		}
		out.Page = v
	}
	if err := readBody(); err != nil {
		return out, err
	}
	if raw, ok := jsonBody["filter"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("filter", "invalid string", err)
		}
		out.Filter = v
	} else if formBody != nil {
		if fv, ok := formBody["filter"]; ok {
			out.Filter = fv
		}
	}
	return out, nil
}

func writeSearchRequest(w http.ResponseWriter, r *http.Request, v SearchRequest) error {
	_ = r
	return httpbind.WriteJSON(w, http.StatusOK, encodeSearchRequestMap(v))
}

func decodeSearchResponseBytes(data []byte) (SearchResponse, error) {
	return decodeSearchResponseJSON(json.RawMessage(data))
}

func decodeSearchResponseJSON(raw json.RawMessage) (SearchResponse, error) {
	var out SearchResponse
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["keyword"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("keyword", "invalid string", err)
		}
		out.Keyword = v
	}
	if raw, ok := m["page"]; ok {
		v, err := jsonbind.DecodeJSONInt(raw)
		if err != nil {
			return out, jsonbind.FieldError("page", "invalid int", err)
		}
		out.Page = v
	}
	if raw, ok := m["filter"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("filter", "invalid string", err)
		}
		out.Filter = v
	}
	return out, nil
}

func encodeSearchResponseMap(v SearchResponse) map[string]any {
	body := map[string]any{}
	body["keyword"] = v.Keyword
	body["page"] = v.Page
	body["filter"] = v.Filter
	return body
}

func encodeSearchResponse(w io.Writer, v SearchResponse) error {
	return json.NewEncoder(w).Encode(encodeSearchResponseMap(v))
}

func bindSearchResponse(r *http.Request) (SearchResponse, error) {
	var out SearchResponse
	var jsonBody map[string]jsonRaw
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbind.IsJSONRequest(r) {
			m, err := httpbind.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbind.IsFormRequest(r) {
			m, err := httpbind.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbind.IsMultipartRequest(r) {
			m, _, err := httpbind.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if qv, ok := httpbind.QueryValue(r, "keyword"); ok {
		out.Keyword = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["keyword"]; ok {
			v, err := jsonbind.DecodeJSONString(raw)
			if err != nil {
				return out, jsonbind.FieldError("keyword", "invalid string", err)
			}
			out.Keyword = v
		} else if formBody != nil {
			if fv, ok := formBody["keyword"]; ok {
				out.Keyword = fv
			}
		}
	}
	if qv, ok := httpbind.QueryValue(r, "page"); ok {
		v, err := httpbind.ParseInt(qv)
		if err != nil {
			return out, httpbind.BindError("page", "query", "invalid int")
		}
		out.Page = v
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["page"]; ok {
			v, err := jsonbind.DecodeJSONInt(raw)
			if err != nil {
				return out, jsonbind.FieldError("page", "invalid int", err)
			}
			out.Page = v
		} else if formBody != nil {
			if fv, ok := formBody["page"]; ok {
				v, err := httpbind.ParseInt(fv)
				if err != nil {
					return out, httpbind.BindError("page", "payload", "invalid int")
				}
				out.Page = v
			}
		}
	}
	if qv, ok := httpbind.QueryValue(r, "filter"); ok {
		out.Filter = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["filter"]; ok {
			v, err := jsonbind.DecodeJSONString(raw)
			if err != nil {
				return out, jsonbind.FieldError("filter", "invalid string", err)
			}
			out.Filter = v
		} else if formBody != nil {
			if fv, ok := formBody["filter"]; ok {
				out.Filter = fv
			}
		}
	}
	return out, nil
}

func writeSearchResponse(w http.ResponseWriter, r *http.Request, v SearchResponse) error {
	_ = r
	return httpbind.WriteJSON(w, http.StatusOK, encodeSearchResponseMap(v))
}

func decodeUploadAvatarRequestBytes(data []byte) (UploadAvatarRequest, error) {
	return decodeUploadAvatarRequestJSON(json.RawMessage(data))
}

func decodeUploadAvatarRequestJSON(raw json.RawMessage) (UploadAvatarRequest, error) {
	var out UploadAvatarRequest
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["title"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("title", "invalid string", err)
		}
		out.Title = v
	}
	return out, nil
}

func encodeUploadAvatarRequestMap(v UploadAvatarRequest) map[string]any {
	body := map[string]any{}
	body["user_id"] = v.UserID
	body["title"] = v.Title
	body["image"] = v.Image
	return body
}

func encodeUploadAvatarRequest(w io.Writer, v UploadAvatarRequest) error {
	return json.NewEncoder(w).Encode(encodeUploadAvatarRequestMap(v))
}

func bindUploadAvatarRequest(r *http.Request) (UploadAvatarRequest, error) {
	var out UploadAvatarRequest
	var jsonBody map[string]jsonRaw
	var formBody map[string]string
	var fileBody map[string]httpbind.File
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbind.IsJSONRequest(r) {
			m, err := httpbind.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbind.IsFormRequest(r) {
			m, err := httpbind.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbind.IsMultipartRequest(r) {
			m, files, err := httpbind.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			fileBody = files
			return nil
		}
		return nil
	}
	out.UserID = httpbind.PathValue(r, "user_id")
	if err := readBody(); err != nil {
		return out, err
	}
	if raw, ok := jsonBody["title"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("title", "invalid string", err)
		}
		out.Title = v
	} else if formBody != nil {
		if fv, ok := formBody["title"]; ok {
			out.Title = fv
		}
	}
	if err := readBody(); err != nil {
		return out, err
	}
	if fv, ok := fileBody["image"]; ok {
		out.Image = fv
	} else if fileBody != nil {
		return out, httpbind.BindError("image", "payload", "missing file")
	}
	return out, nil
}

func writeUploadAvatarRequest(w http.ResponseWriter, r *http.Request, v UploadAvatarRequest) error {
	_ = r
	return httpbind.WriteJSON(w, http.StatusOK, encodeUploadAvatarRequestMap(v))
}

func decodePatchWithExtrasRequestBytes(data []byte) (PatchWithExtrasRequest, error) {
	return decodePatchWithExtrasRequestJSON(json.RawMessage(data))
}

func decodePatchWithExtrasRequestJSON(raw json.RawMessage) (PatchWithExtrasRequest, error) {
	var out PatchWithExtrasRequest
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["name"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("name", "invalid string", err)
		}
		out.Name = v
	}
	if raw, ok := m["email"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("email", "invalid string", err)
		}
		out.Email = v
	}
	{
		rm, err := jsonbind.RestJSONAny(m, []string{"name", "email"})
		if err != nil {
			return out, err
		}
		out.Extra = rm
	}
	return out, nil
}

func encodePatchWithExtrasRequestMap(v PatchWithExtrasRequest) map[string]any {
	body := map[string]any{}
	body["name"] = v.Name
	body["email"] = v.Email
	for k, val := range v.Extra {
		body[k] = val
	}
	return body
}

func encodePatchWithExtrasRequest(w io.Writer, v PatchWithExtrasRequest) error {
	return json.NewEncoder(w).Encode(encodePatchWithExtrasRequestMap(v))
}

func bindPatchWithExtrasRequest(r *http.Request) (PatchWithExtrasRequest, error) {
	var out PatchWithExtrasRequest
	var jsonBody map[string]jsonRaw
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbind.IsJSONRequest(r) {
			m, err := httpbind.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbind.IsFormRequest(r) {
			m, err := httpbind.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbind.IsMultipartRequest(r) {
			m, _, err := httpbind.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if err := readBody(); err != nil {
		return out, err
	}
	if raw, ok := jsonBody["name"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("name", "invalid string", err)
		}
		out.Name = v
	} else if formBody != nil {
		if fv, ok := formBody["name"]; ok {
			out.Name = fv
		}
	}
	if err := readBody(); err != nil {
		return out, err
	}
	if raw, ok := jsonBody["email"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("email", "invalid string", err)
		}
		out.Email = v
	} else if formBody != nil {
		if fv, ok := formBody["email"]; ok {
			out.Email = fv
		}
	}
	if err := readBody(); err != nil {
		return out, err
	}
	if jsonBody != nil {
		m, err := jsonbind.RestJSONAny(jsonBody, []string{"name", "email"})
		if err != nil {
			return out, err
		}
		out.Extra = m
	} else if formBody != nil {
		out.Extra = httpbind.RestFormAny(formBody, []string{"name", "email"})
	} else {
		out.Extra = map[string]any{}
	}
	return out, nil
}

func writePatchWithExtrasRequest(w http.ResponseWriter, r *http.Request, v PatchWithExtrasRequest) error {
	_ = r
	return httpbind.WriteJSON(w, http.StatusOK, encodePatchWithExtrasRequestMap(v))
}

func decodePatchWithExtrasRawRequestBytes(data []byte) (PatchWithExtrasRawRequest, error) {
	return decodePatchWithExtrasRawRequestJSON(json.RawMessage(data))
}

func decodePatchWithExtrasRawRequestJSON(raw json.RawMessage) (PatchWithExtrasRawRequest, error) {
	var out PatchWithExtrasRawRequest
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["name"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("name", "invalid string", err)
		}
		out.Name = v
	}
	out.Extra = jsonbind.RestJSONRaw(m, []string{"name"})
	return out, nil
}

func encodePatchWithExtrasRawRequestMap(v PatchWithExtrasRawRequest) map[string]any {
	body := map[string]any{}
	body["name"] = v.Name
	for k, val := range v.Extra {
		body[k] = val
	}
	return body
}

func encodePatchWithExtrasRawRequest(w io.Writer, v PatchWithExtrasRawRequest) error {
	return json.NewEncoder(w).Encode(encodePatchWithExtrasRawRequestMap(v))
}

func bindPatchWithExtrasRawRequest(r *http.Request) (PatchWithExtrasRawRequest, error) {
	var out PatchWithExtrasRawRequest
	var jsonBody map[string]jsonRaw
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbind.IsJSONRequest(r) {
			m, err := httpbind.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbind.IsFormRequest(r) {
			m, err := httpbind.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbind.IsMultipartRequest(r) {
			m, _, err := httpbind.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if err := readBody(); err != nil {
		return out, err
	}
	if raw, ok := jsonBody["name"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("name", "invalid string", err)
		}
		out.Name = v
	} else if formBody != nil {
		if fv, ok := formBody["name"]; ok {
			out.Name = fv
		}
	}
	if err := readBody(); err != nil {
		return out, err
	}
	if jsonBody != nil {
		out.Extra = jsonbind.RestJSONRaw(jsonBody, []string{"name"})
	} else if formBody != nil {
		out.Extra = httpbind.RestFormRaw(formBody, []string{"name"})
	} else {
		out.Extra = map[string]json.RawMessage{}
	}
	return out, nil
}

func writePatchWithExtrasRawRequest(w http.ResponseWriter, r *http.Request, v PatchWithExtrasRawRequest) error {
	_ = r
	return httpbind.WriteJSON(w, http.StatusOK, encodePatchWithExtrasRawRequestMap(v))
}

func decodeNestedCustomerBytes(data []byte) (NestedCustomer, error) {
	return decodeNestedCustomerJSON(json.RawMessage(data))
}

func decodeNestedCustomerJSON(raw json.RawMessage) (NestedCustomer, error) {
	var out NestedCustomer
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["id"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("id", "invalid string", err)
		}
		out.ID = v
	}
	if raw, ok := m["name"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("name", "invalid string", err)
		}
		out.Name = v
	}
	return out, nil
}

func encodeNestedCustomerMap(v NestedCustomer) map[string]any {
	body := map[string]any{}
	body["id"] = v.ID
	body["name"] = v.Name
	return body
}

func encodeNestedCustomer(w io.Writer, v NestedCustomer) error {
	return json.NewEncoder(w).Encode(encodeNestedCustomerMap(v))
}

func bindNestedCustomer(r *http.Request) (NestedCustomer, error) {
	var out NestedCustomer
	var jsonBody map[string]jsonRaw
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbind.IsJSONRequest(r) {
			m, err := httpbind.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbind.IsFormRequest(r) {
			m, err := httpbind.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbind.IsMultipartRequest(r) {
			m, _, err := httpbind.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if err := readBody(); err != nil {
		return out, err
	}
	if raw, ok := jsonBody["id"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("id", "invalid string", err)
		}
		out.ID = v
	} else if formBody != nil {
		if fv, ok := formBody["id"]; ok {
			out.ID = fv
		}
	}
	if err := readBody(); err != nil {
		return out, err
	}
	if raw, ok := jsonBody["name"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("name", "invalid string", err)
		}
		out.Name = v
	} else if formBody != nil {
		if fv, ok := formBody["name"]; ok {
			out.Name = fv
		}
	}
	return out, nil
}

func writeNestedCustomer(w http.ResponseWriter, r *http.Request, v NestedCustomer) error {
	_ = r
	return httpbind.WriteJSON(w, http.StatusOK, encodeNestedCustomerMap(v))
}

func decodeNestedLineItemBytes(data []byte) (NestedLineItem, error) {
	return decodeNestedLineItemJSON(json.RawMessage(data))
}

func decodeNestedLineItemJSON(raw json.RawMessage) (NestedLineItem, error) {
	var out NestedLineItem
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["sku"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("sku", "invalid string", err)
		}
		out.SKU = v
	}
	if raw, ok := m["qty"]; ok {
		v, err := jsonbind.DecodeJSONInt(raw)
		if err != nil {
			return out, jsonbind.FieldError("qty", "invalid int", err)
		}
		out.Qty = v
	}
	return out, nil
}

func encodeNestedLineItemMap(v NestedLineItem) map[string]any {
	body := map[string]any{}
	body["sku"] = v.SKU
	body["qty"] = v.Qty
	return body
}

func encodeNestedLineItem(w io.Writer, v NestedLineItem) error {
	return json.NewEncoder(w).Encode(encodeNestedLineItemMap(v))
}

func bindNestedLineItem(r *http.Request) (NestedLineItem, error) {
	var out NestedLineItem
	var jsonBody map[string]jsonRaw
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbind.IsJSONRequest(r) {
			m, err := httpbind.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbind.IsFormRequest(r) {
			m, err := httpbind.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbind.IsMultipartRequest(r) {
			m, _, err := httpbind.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if err := readBody(); err != nil {
		return out, err
	}
	if raw, ok := jsonBody["sku"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("sku", "invalid string", err)
		}
		out.SKU = v
	} else if formBody != nil {
		if fv, ok := formBody["sku"]; ok {
			out.SKU = fv
		}
	}
	if err := readBody(); err != nil {
		return out, err
	}
	if raw, ok := jsonBody["qty"]; ok {
		v, err := jsonbind.DecodeJSONInt(raw)
		if err != nil {
			return out, jsonbind.FieldError("qty", "invalid int", err)
		}
		out.Qty = v
	} else if formBody != nil {
		if fv, ok := formBody["qty"]; ok {
			v, err := httpbind.ParseInt(fv)
			if err != nil {
				return out, httpbind.BindError("qty", "payload", "invalid int")
			}
			out.Qty = v
		}
	}
	return out, nil
}

func writeNestedLineItem(w http.ResponseWriter, r *http.Request, v NestedLineItem) error {
	_ = r
	return httpbind.WriteJSON(w, http.StatusOK, encodeNestedLineItemMap(v))
}

func decodeNestedOrderRequestBytes(data []byte) (NestedOrderRequest, error) {
	return decodeNestedOrderRequestJSON(json.RawMessage(data))
}

func decodeNestedOrderRequestJSON(raw json.RawMessage) (NestedOrderRequest, error) {
	var out NestedOrderRequest
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["customer"]; ok {
		v, err := decodeNestedCustomerJSON(raw)
		if err != nil {
			return out, err
		}
		out.Customer = v
	}
	if raw, ok := m["items"]; ok {
		arr, err := jsonbind.RawJSONArray(raw)
		if err != nil {
			return out, err
		}
		slice := make([]NestedLineItem, 0, len(arr))
		for _, el := range arr {
			item, err := decodeNestedLineItemJSON(el)
			if err != nil {
				return out, err
			}
			slice = append(slice, item)
		}
		out.Items = slice
	}
	if raw, ok := m["labels"]; ok {
		v, err := jsonbind.DecodeJSONMapStringString(raw)
		if err != nil {
			return out, err
		}
		out.Labels = v
	}
	return out, nil
}

func encodeNestedOrderRequestMap(v NestedOrderRequest) map[string]any {
	body := map[string]any{}
	body["customer"] = encodeNestedCustomerMap(v.Customer)
	{
		arr := make([]any, len(v.Items))
		for i := range v.Items {
			arr[i] = encodeNestedLineItemMap(v.Items[i])
		}
		body["items"] = arr
	}
	body["labels"] = v.Labels
	return body
}

func encodeNestedOrderRequest(w io.Writer, v NestedOrderRequest) error {
	return json.NewEncoder(w).Encode(encodeNestedOrderRequestMap(v))
}

func bindNestedOrderRequest(r *http.Request) (NestedOrderRequest, error) {
	var out NestedOrderRequest
	var jsonBody map[string]jsonRaw
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbind.IsJSONRequest(r) {
			m, err := httpbind.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		return nil
	}
	if err := readBody(); err != nil {
		return out, err
	}
	if raw, ok := jsonBody["customer"]; ok {
		v, err := decodeNestedCustomerJSON(raw)
		if err != nil {
			return out, err
		}
		out.Customer = v
	}
	if err := readBody(); err != nil {
		return out, err
	}
	if raw, ok := jsonBody["items"]; ok {
		arr, err := jsonbind.RawJSONArray(raw)
		if err != nil {
			return out, err
		}
		slice := make([]NestedLineItem, 0, len(arr))
		for _, el := range arr {
			item, err := decodeNestedLineItemJSON(el)
			if err != nil {
				return out, err
			}
			slice = append(slice, item)
		}
		out.Items = slice
	}
	if err := readBody(); err != nil {
		return out, err
	}
	if raw, ok := jsonBody["labels"]; ok {
		v, err := jsonbind.DecodeJSONMapStringString(raw)
		if err != nil {
			return out, err
		}
		out.Labels = v
	}
	return out, nil
}

func writeNestedOrderRequest(w http.ResponseWriter, r *http.Request, v NestedOrderRequest) error {
	_ = r
	return httpbind.WriteJSON(w, http.StatusOK, encodeNestedOrderRequestMap(v))
}

func decodeCodecOnlyNoteBytes(data []byte) (CodecOnlyNote, error) {
	return decodeCodecOnlyNoteJSON(json.RawMessage(data))
}

func decodeCodecOnlyNoteJSON(raw json.RawMessage) (CodecOnlyNote, error) {
	var out CodecOnlyNote
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["text"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("text", "invalid string", err)
		}
		out.Text = v
	}
	if raw, ok := m["n"]; ok {
		v, err := jsonbind.DecodeJSONInt(raw)
		if err != nil {
			return out, jsonbind.FieldError("n", "invalid int", err)
		}
		out.N = v
	}
	return out, nil
}

func encodeCodecOnlyNoteMap(v CodecOnlyNote) map[string]any {
	body := map[string]any{}
	body["text"] = v.Text
	body["n"] = v.N
	return body
}

func encodeCodecOnlyNote(w io.Writer, v CodecOnlyNote) error {
	return json.NewEncoder(w).Encode(encodeCodecOnlyNoteMap(v))
}

func bindCodecOnlyNote(r *http.Request) (CodecOnlyNote, error) {
	var out CodecOnlyNote
	var jsonBody map[string]jsonRaw
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbind.IsJSONRequest(r) {
			m, err := httpbind.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbind.IsFormRequest(r) {
			m, err := httpbind.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbind.IsMultipartRequest(r) {
			m, _, err := httpbind.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if err := readBody(); err != nil {
		return out, err
	}
	if raw, ok := jsonBody["text"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("text", "invalid string", err)
		}
		out.Text = v
	} else if formBody != nil {
		if fv, ok := formBody["text"]; ok {
			out.Text = fv
		}
	}
	if err := readBody(); err != nil {
		return out, err
	}
	if raw, ok := jsonBody["n"]; ok {
		v, err := jsonbind.DecodeJSONInt(raw)
		if err != nil {
			return out, jsonbind.FieldError("n", "invalid int", err)
		}
		out.N = v
	} else if formBody != nil {
		if fv, ok := formBody["n"]; ok {
			v, err := httpbind.ParseInt(fv)
			if err != nil {
				return out, httpbind.BindError("n", "payload", "invalid int")
			}
			out.N = v
		}
	}
	return out, nil
}

func writeCodecOnlyNote(w http.ResponseWriter, r *http.Request, v CodecOnlyNote) error {
	_ = r
	return httpbind.WriteJSON(w, http.StatusOK, encodeCodecOnlyNoteMap(v))
}
