// Code generated by tinybind; DO NOT EDIT.

package checkfixture

import (
	"encoding/json"
	"io"
	"net/http"
	"regexp"

	"github.com/shibukawa/tinybind-go"
	"github.com/shibukawa/tinybind-go/jsonbind"
)

type jsonRaw = json.RawMessage

var checkPatternCheckRequestCode = regexp.MustCompile("^[A-Z]{3}$")

func init() {
	httpbind.RegisterBind[CheckRequest](bindCheckRequest)
	httpbind.RegisterWrite[CheckRequest](writeCheckRequest)
	jsonbind.RegisterDecode[CheckRequest](decodeCheckRequestBytes)
	jsonbind.RegisterEncode[CheckRequest](encodeCheckRequest)
	httpbind.RegisterBind[CheckResponse](bindCheckResponse)
	httpbind.RegisterWrite[CheckResponse](writeCheckResponse)
	jsonbind.RegisterDecode[CheckResponse](decodeCheckResponseBytes)
	jsonbind.RegisterEncode[CheckResponse](encodeCheckResponse)
	httpbind.RegisterBind[OpenAPICheckRequest](bindOpenAPICheckRequest)
	httpbind.RegisterWrite[OpenAPICheckRequest](writeOpenAPICheckRequest)
	jsonbind.RegisterDecode[OpenAPICheckRequest](decodeOpenAPICheckRequestBytes)
	jsonbind.RegisterEncode[OpenAPICheckRequest](encodeOpenAPICheckRequest)
	httpbind.RegisterBind[OpenAPICheckResponse](bindOpenAPICheckResponse)
	httpbind.RegisterWrite[OpenAPICheckResponse](writeOpenAPICheckResponse)
	jsonbind.RegisterDecode[OpenAPICheckResponse](decodeOpenAPICheckResponseBytes)
	jsonbind.RegisterEncode[OpenAPICheckResponse](encodeOpenAPICheckResponse)
}

func decodeCheckRequestBytes(data []byte) (CheckRequest, error) {
	return decodeCheckRequestJSON(json.RawMessage(data))
}

func decodeCheckRequestJSON(raw json.RawMessage) (CheckRequest, error) {
	var out CheckRequest
	_ = raw
	return out, nil
}

func encodeCheckRequestMap(v CheckRequest) map[string]any {
	body := map[string]any{}
	body["name"] = v.Name
	body["email"] = v.Email
	body["age"] = v.Age
	body["sort"] = v.Sort
	body["code"] = v.Code
	body["id"] = v.ID
	body["born"] = v.Born
	body["at"] = v.At
	body["when"] = v.When
	body["page"] = v.Page
	body["optional"] = v.Optional
	return body
}

func encodeCheckRequest(w io.Writer, v CheckRequest) error {
	return json.NewEncoder(w).Encode(encodeCheckRequestMap(v))
}

func bindCheckRequest(r *http.Request) (CheckRequest, error) {
	var out CheckRequest
	var presentName bool
	var presentEmail bool
	var presentAge bool
	var presentSort bool
	var presentCode bool
	var presentID bool
	var presentBorn bool
	var presentAt bool
	var presentWhen bool
	var presentPage bool
	var presentOptional bool
	if qv, ok := httpbind.QueryValue(r, "name"); ok {
		presentName = true
		out.Name = qv
	}
	if qv, ok := httpbind.QueryValue(r, "email"); ok {
		presentEmail = true
		out.Email = qv
	}
	if qv, ok := httpbind.QueryValue(r, "age"); ok {
		presentAge = true
		v, err := httpbind.ParseInt(qv)
		if err != nil {
			return out, httpbind.BindError("age", "query", "invalid int")
		}
		out.Age = v
	}
	if qv, ok := httpbind.QueryValue(r, "sort"); ok {
		presentSort = true
		out.Sort = qv
	}
	if qv, ok := httpbind.QueryValue(r, "code"); ok {
		presentCode = true
		out.Code = qv
	}
	if qv, ok := httpbind.QueryValue(r, "id"); ok {
		presentID = true
		out.ID = qv
	}
	if qv, ok := httpbind.QueryValue(r, "born"); ok {
		presentBorn = true
		out.Born = qv
	}
	if qv, ok := httpbind.QueryValue(r, "at"); ok {
		presentAt = true
		out.At = qv
	}
	if qv, ok := httpbind.QueryValue(r, "when"); ok {
		presentWhen = true
		out.When = qv
	}
	if qv, ok := httpbind.QueryValue(r, "page"); ok {
		presentPage = true
		v, err := httpbind.ParseInt(qv)
		if err != nil {
			return out, httpbind.BindError("page", "query", "invalid int")
		}
		out.Page = v
	}
	if qv, ok := httpbind.QueryValue(r, "optional"); ok {
		presentOptional = true
		out.Optional = qv
	}
	var checkFields []httpbind.FieldError
	if !presentName || out.Name == "" {
		checkFields = append(checkFields, httpbind.Field("name", "query", "required"))
	}
	if presentName {
		if len(out.Name) < 1 {
			checkFields = append(checkFields, httpbind.Field("name", "query", "length must be >= 1"))
		}
		if len(out.Name) > 64 {
			checkFields = append(checkFields, httpbind.Field("name", "query", "length must be <= 64"))
		}
	}
	if !presentEmail || out.Email == "" {
		checkFields = append(checkFields, httpbind.Field("email", "query", "required"))
	}
	if presentEmail {
		if len(out.Email) > 254 {
			checkFields = append(checkFields, httpbind.Field("email", "query", "length must be <= 254"))
		}
		if out.Email != "" {
			if !httpbind.CheckEmail(out.Email) {
				checkFields = append(checkFields, httpbind.Field("email", "query", "must be a valid email"))
			}
		}
	}
	if presentAge {
		if out.Age < 0 {
			checkFields = append(checkFields, httpbind.Field("age", "query", "must be >= 0"))
		}
		if out.Age > 150 {
			checkFields = append(checkFields, httpbind.Field("age", "query", "must be <= 150"))
		}
	}
	if presentSort {
		{
			enumOK := false
			if out.Sort == "asc" {
				enumOK = true
			}
			if out.Sort == "desc" {
				enumOK = true
			}
			if !enumOK {
				checkFields = append(checkFields, httpbind.Field("sort", "query", "must be one of: asc, desc"))
			}
		}
	}
	if presentCode {
		if out.Code != "" {
			if !checkPatternCheckRequestCode.MatchString(out.Code) {
				checkFields = append(checkFields, httpbind.Field("code", "query", "must match pattern"))
			}
		}
	}
	if presentID {
		if out.ID != "" {
			if !httpbind.CheckUUID(out.ID) {
				checkFields = append(checkFields, httpbind.Field("id", "query", "must be a valid uuid"))
			}
		}
	}
	if presentBorn {
		if out.Born != "" {
			if !httpbind.CheckDate(out.Born) {
				checkFields = append(checkFields, httpbind.Field("born", "query", "must be ISO date"))
			}
		}
	}
	if presentAt {
		if out.At != "" {
			if !httpbind.CheckTime(out.At) {
				checkFields = append(checkFields, httpbind.Field("at", "query", "must be ISO time"))
			}
		}
	}
	if presentWhen {
		if out.When != "" {
			if !httpbind.CheckDateTime(out.When) {
				checkFields = append(checkFields, httpbind.Field("when", "query", "must be RFC3339 datetime"))
			}
		}
	}
	if presentPage {
		if out.Page < 1 {
			checkFields = append(checkFields, httpbind.Field("page", "query", "must be >= 1"))
		}
	}
	if presentOptional {
		if out.Optional != "" {
			if !httpbind.CheckEmail(out.Optional) {
				checkFields = append(checkFields, httpbind.Field("optional", "query", "must be a valid email"))
			}
		}
	}
	if len(checkFields) > 0 {
		return out, httpbind.Validation(checkFields...)
	}
	if !presentPage {
		out.Page = -1
	}
	return out, nil
}

func writeCheckRequest(w http.ResponseWriter, r *http.Request, v CheckRequest) error {
	_ = r
	return httpbind.WriteJSON(w, http.StatusOK, encodeCheckRequestMap(v))
}

func decodeCheckResponseBytes(data []byte) (CheckResponse, error) {
	return decodeCheckResponseJSON(json.RawMessage(data))
}

func decodeCheckResponseJSON(raw json.RawMessage) (CheckResponse, error) {
	var out CheckResponse
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["ok"]; ok {
		v, err := jsonbind.DecodeJSONBool(raw)
		if err != nil {
			return out, jsonbind.FieldError("oK", "invalid bool", err)
		}
		out.OK = v
	}
	return out, nil
}

func encodeCheckResponseMap(v CheckResponse) map[string]any {
	body := map[string]any{}
	body["ok"] = v.OK
	return body
}

func encodeCheckResponse(w io.Writer, v CheckResponse) error {
	return json.NewEncoder(w).Encode(encodeCheckResponseMap(v))
}

func bindCheckResponse(r *http.Request) (CheckResponse, error) {
	var out CheckResponse
	var jsonBody map[string]jsonRaw
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbind.IsJSONRequest(r) {
			m, err := httpbind.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbind.IsFormRequest(r) {
			m, err := httpbind.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbind.IsMultipartRequest(r) {
			m, _, err := httpbind.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if qv, ok := httpbind.QueryValue(r, "oK"); ok {
		v, err := httpbind.ParseBool(qv)
		if err != nil {
			return out, httpbind.BindError("oK", "query", "invalid bool")
		}
		out.OK = v
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["oK"]; ok {
			v, err := jsonbind.DecodeJSONBool(raw)
			if err != nil {
				return out, jsonbind.FieldError("oK", "invalid bool", err)
			}
			out.OK = v
		} else if formBody != nil {
			if fv, ok := formBody["oK"]; ok {
				v, err := httpbind.ParseBool(fv)
				if err != nil {
					return out, httpbind.BindError("oK", "payload", "invalid bool")
				}
				out.OK = v
			}
		}
	}
	return out, nil
}

func writeCheckResponse(w http.ResponseWriter, r *http.Request, v CheckResponse) error {
	_ = r
	return httpbind.WriteJSON(w, http.StatusOK, encodeCheckResponseMap(v))
}

func decodeOpenAPICheckRequestBytes(data []byte) (OpenAPICheckRequest, error) {
	return decodeOpenAPICheckRequestJSON(json.RawMessage(data))
}

func decodeOpenAPICheckRequestJSON(raw json.RawMessage) (OpenAPICheckRequest, error) {
	var out OpenAPICheckRequest
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["name"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("name", "invalid string", err)
		}
		out.Name = v
	}
	if raw, ok := m["age"]; ok {
		v, err := jsonbind.DecodeJSONInt(raw)
		if err != nil {
			return out, jsonbind.FieldError("age", "invalid int", err)
		}
		out.Age = v
	}
	if raw, ok := m["email"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("email", "invalid string", err)
		}
		out.Email = v
	}
	return out, nil
}

func encodeOpenAPICheckRequestMap(v OpenAPICheckRequest) map[string]any {
	body := map[string]any{}
	body["name"] = v.Name
	body["age"] = v.Age
	body["sort"] = v.Sort
	body["email"] = v.Email
	return body
}

func encodeOpenAPICheckRequest(w io.Writer, v OpenAPICheckRequest) error {
	return json.NewEncoder(w).Encode(encodeOpenAPICheckRequestMap(v))
}

func bindOpenAPICheckRequest(r *http.Request) (OpenAPICheckRequest, error) {
	var out OpenAPICheckRequest
	var presentName bool
	var presentAge bool
	var presentSort bool
	var presentEmail bool
	var jsonBody map[string]jsonRaw
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbind.IsJSONRequest(r) {
			m, err := httpbind.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbind.IsFormRequest(r) {
			m, err := httpbind.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbind.IsMultipartRequest(r) {
			m, _, err := httpbind.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if err := readBody(); err != nil {
		return out, err
	}
	if raw, ok := jsonBody["name"]; ok {
		presentName = true
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("name", "invalid string", err)
		}
		out.Name = v
	} else if formBody != nil {
		if fv, ok := formBody["name"]; ok {
			presentName = true
			out.Name = fv
		}
	}
	if err := readBody(); err != nil {
		return out, err
	}
	if raw, ok := jsonBody["age"]; ok {
		presentAge = true
		v, err := jsonbind.DecodeJSONInt(raw)
		if err != nil {
			return out, jsonbind.FieldError("age", "invalid int", err)
		}
		out.Age = v
	} else if formBody != nil {
		if fv, ok := formBody["age"]; ok {
			presentAge = true
			v, err := httpbind.ParseInt(fv)
			if err != nil {
				return out, httpbind.BindError("age", "payload", "invalid int")
			}
			out.Age = v
		}
	}
	if qv, ok := httpbind.QueryValue(r, "sort"); ok {
		presentSort = true
		out.Sort = qv
	}
	if err := readBody(); err != nil {
		return out, err
	}
	if raw, ok := jsonBody["email"]; ok {
		presentEmail = true
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("email", "invalid string", err)
		}
		out.Email = v
	} else if formBody != nil {
		if fv, ok := formBody["email"]; ok {
			presentEmail = true
			out.Email = fv
		}
	}
	var checkFields []httpbind.FieldError
	if !presentName || out.Name == "" {
		checkFields = append(checkFields, httpbind.Field("name", "payload", "required"))
	}
	if presentName {
		if len(out.Name) < 1 {
			checkFields = append(checkFields, httpbind.Field("name", "payload", "length must be >= 1"))
		}
	}
	if presentAge {
		if out.Age < 1 {
			checkFields = append(checkFields, httpbind.Field("age", "payload", "must be >= 1"))
		}
		if out.Age > 120 {
			checkFields = append(checkFields, httpbind.Field("age", "payload", "must be <= 120"))
		}
	}
	if presentSort {
		{
			enumOK := false
			if out.Sort == "asc" {
				enumOK = true
			}
			if out.Sort == "desc" {
				enumOK = true
			}
			if !enumOK {
				checkFields = append(checkFields, httpbind.Field("sort", "query", "must be one of: asc, desc"))
			}
		}
	}
	if presentEmail {
		if out.Email != "" {
			if !httpbind.CheckEmail(out.Email) {
				checkFields = append(checkFields, httpbind.Field("email", "payload", "must be a valid email"))
			}
		}
	}
	if len(checkFields) > 0 {
		return out, httpbind.Validation(checkFields...)
	}
	if !presentSort {
		out.Sort = "asc"
	}
	return out, nil
}

func writeOpenAPICheckRequest(w http.ResponseWriter, r *http.Request, v OpenAPICheckRequest) error {
	_ = r
	return httpbind.WriteJSON(w, http.StatusOK, encodeOpenAPICheckRequestMap(v))
}

func decodeOpenAPICheckResponseBytes(data []byte) (OpenAPICheckResponse, error) {
	return decodeOpenAPICheckResponseJSON(json.RawMessage(data))
}

func decodeOpenAPICheckResponseJSON(raw json.RawMessage) (OpenAPICheckResponse, error) {
	var out OpenAPICheckResponse
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["ok"]; ok {
		v, err := jsonbind.DecodeJSONBool(raw)
		if err != nil {
			return out, jsonbind.FieldError("oK", "invalid bool", err)
		}
		out.OK = v
	}
	return out, nil
}

func encodeOpenAPICheckResponseMap(v OpenAPICheckResponse) map[string]any {
	body := map[string]any{}
	body["ok"] = v.OK
	return body
}

func encodeOpenAPICheckResponse(w io.Writer, v OpenAPICheckResponse) error {
	return json.NewEncoder(w).Encode(encodeOpenAPICheckResponseMap(v))
}

func bindOpenAPICheckResponse(r *http.Request) (OpenAPICheckResponse, error) {
	var out OpenAPICheckResponse
	var jsonBody map[string]jsonRaw
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbind.IsJSONRequest(r) {
			m, err := httpbind.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbind.IsFormRequest(r) {
			m, err := httpbind.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbind.IsMultipartRequest(r) {
			m, _, err := httpbind.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if qv, ok := httpbind.QueryValue(r, "oK"); ok {
		v, err := httpbind.ParseBool(qv)
		if err != nil {
			return out, httpbind.BindError("oK", "query", "invalid bool")
		}
		out.OK = v
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["oK"]; ok {
			v, err := jsonbind.DecodeJSONBool(raw)
			if err != nil {
				return out, jsonbind.FieldError("oK", "invalid bool", err)
			}
			out.OK = v
		} else if formBody != nil {
			if fv, ok := formBody["oK"]; ok {
				v, err := httpbind.ParseBool(fv)
				if err != nil {
					return out, httpbind.BindError("oK", "payload", "invalid bool")
				}
				out.OK = v
			}
		}
	}
	return out, nil
}

func writeOpenAPICheckResponse(w http.ResponseWriter, r *http.Request, v OpenAPICheckResponse) error {
	_ = r
	return httpbind.WriteJSON(w, http.StatusOK, encodeOpenAPICheckResponseMap(v))
}
