// Code generated by tinybind; DO NOT EDIT.

package tinycheck

import (
	"encoding/json"
	"io"
	"net/http"

	"github.com/shibukawa/tinybind-go"
	"github.com/shibukawa/tinybind-go/jsonbind"
)

type jsonRaw = json.RawMessage

func init() {
	httpbind.RegisterBind[CreateUserRequest](bindCreateUserRequest)
	httpbind.RegisterWrite[CreateUserRequest](writeCreateUserRequest)
	jsonbind.RegisterDecode[CreateUserRequest](decodeCreateUserRequestBytes)
	jsonbind.RegisterEncode[CreateUserRequest](encodeCreateUserRequest)
	httpbind.RegisterBind[CreateUserResponse](bindCreateUserResponse)
	httpbind.RegisterWrite[CreateUserResponse](writeCreateUserResponse)
	jsonbind.RegisterDecode[CreateUserResponse](decodeCreateUserResponseBytes)
	jsonbind.RegisterEncode[CreateUserResponse](encodeCreateUserResponse)
}

func decodeCreateUserRequestBytes(data []byte) (CreateUserRequest, error) {
	return decodeCreateUserRequestJSON(json.RawMessage(data))
}

func decodeCreateUserRequestJSON(raw json.RawMessage) (CreateUserRequest, error) {
	var out CreateUserRequest
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["name"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("name", "invalid string", err)
		}
		out.Name = v
	}
	if raw, ok := m["email"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("email", "invalid string", err)
		}
		out.Email = v
	}
	return out, nil
}

func encodeCreateUserRequestMap(v CreateUserRequest) map[string]any {
	body := map[string]any{}
	body["name"] = v.Name
	body["email"] = v.Email
	body["org_id"] = v.OrgID
	body["Authorization"] = v.Token
	return body
}

func encodeCreateUserRequest(w io.Writer, v CreateUserRequest) error {
	return json.NewEncoder(w).Encode(encodeCreateUserRequestMap(v))
}

func bindCreateUserRequest(r *http.Request) (CreateUserRequest, error) {
	var out CreateUserRequest
	var jsonBody map[string]jsonRaw
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbind.IsJSONRequest(r) {
			m, err := httpbind.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbind.IsFormRequest(r) {
			m, err := httpbind.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbind.IsMultipartRequest(r) {
			m, _, err := httpbind.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if qv, ok := httpbind.QueryValue(r, "name"); ok {
		out.Name = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["name"]; ok {
			v, err := jsonbind.DecodeJSONString(raw)
			if err != nil {
				return out, jsonbind.FieldError("name", "invalid string", err)
			}
			out.Name = v
		} else if formBody != nil {
			if fv, ok := formBody["name"]; ok {
				out.Name = fv
			}
		}
	}
	if qv, ok := httpbind.QueryValue(r, "email"); ok {
		out.Email = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["email"]; ok {
			v, err := jsonbind.DecodeJSONString(raw)
			if err != nil {
				return out, jsonbind.FieldError("email", "invalid string", err)
			}
			out.Email = v
		} else if formBody != nil {
			if fv, ok := formBody["email"]; ok {
				out.Email = fv
			}
		}
	}
	out.OrgID = httpbind.PathValue(r, "org_id")
	out.Token = httpbind.HeaderValue(r, "Authorization")
	return out, nil
}

func writeCreateUserRequest(w http.ResponseWriter, r *http.Request, v CreateUserRequest) error {
	_ = r
	return httpbind.WriteJSON(w, http.StatusOK, encodeCreateUserRequestMap(v))
}

func decodeCreateUserResponseBytes(data []byte) (CreateUserResponse, error) {
	return decodeCreateUserResponseJSON(json.RawMessage(data))
}

func decodeCreateUserResponseJSON(raw json.RawMessage) (CreateUserResponse, error) {
	var out CreateUserResponse
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["id"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("iD", "invalid string", err)
		}
		out.ID = v
	}
	if raw, ok := m["name"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("name", "invalid string", err)
		}
		out.Name = v
	}
	if raw, ok := m["email"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("email", "invalid string", err)
		}
		out.Email = v
	}
	return out, nil
}

func encodeCreateUserResponseMap(v CreateUserResponse) map[string]any {
	body := map[string]any{}
	body["id"] = v.ID
	body["name"] = v.Name
	body["email"] = v.Email
	return body
}

func encodeCreateUserResponse(w io.Writer, v CreateUserResponse) error {
	return json.NewEncoder(w).Encode(encodeCreateUserResponseMap(v))
}

func bindCreateUserResponse(r *http.Request) (CreateUserResponse, error) {
	var out CreateUserResponse
	var jsonBody map[string]jsonRaw
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbind.IsJSONRequest(r) {
			m, err := httpbind.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbind.IsFormRequest(r) {
			m, err := httpbind.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbind.IsMultipartRequest(r) {
			m, _, err := httpbind.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if qv, ok := httpbind.QueryValue(r, "iD"); ok {
		out.ID = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["iD"]; ok {
			v, err := jsonbind.DecodeJSONString(raw)
			if err != nil {
				return out, jsonbind.FieldError("iD", "invalid string", err)
			}
			out.ID = v
		} else if formBody != nil {
			if fv, ok := formBody["iD"]; ok {
				out.ID = fv
			}
		}
	}
	if qv, ok := httpbind.QueryValue(r, "name"); ok {
		out.Name = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["name"]; ok {
			v, err := jsonbind.DecodeJSONString(raw)
			if err != nil {
				return out, jsonbind.FieldError("name", "invalid string", err)
			}
			out.Name = v
		} else if formBody != nil {
			if fv, ok := formBody["name"]; ok {
				out.Name = fv
			}
		}
	}
	if qv, ok := httpbind.QueryValue(r, "email"); ok {
		out.Email = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["email"]; ok {
			v, err := jsonbind.DecodeJSONString(raw)
			if err != nil {
				return out, jsonbind.FieldError("email", "invalid string", err)
			}
			out.Email = v
		} else if formBody != nil {
			if fv, ok := formBody["email"]; ok {
				out.Email = fv
			}
		}
	}
	return out, nil
}

func writeCreateUserResponse(w http.ResponseWriter, r *http.Request, v CreateUserResponse) error {
	_ = r
	return httpbind.WriteJSON(w, http.StatusOK, encodeCreateUserResponseMap(v))
}
