// Code generated by tinybind; DO NOT EDIT.

package openapifixture

import (
	"encoding/json"
	"io"
	"net/http"

	"github.com/shibukawa/tinybind-go"
	"github.com/shibukawa/tinybind-go/jsonbind"
)

type jsonRaw = json.RawMessage

func init() {
	httpbind.RegisterBind[CreateUserRequest](bindCreateUserRequest)
	httpbind.RegisterWrite[CreateUserRequest](writeCreateUserRequest)
	jsonbind.RegisterDecode[CreateUserRequest](decodeCreateUserRequestBytes)
	jsonbind.RegisterEncode[CreateUserRequest](encodeCreateUserRequest)
	httpbind.RegisterBind[CreateUserResponse](bindCreateUserResponse)
	httpbind.RegisterWrite[CreateUserResponse](writeCreateUserResponse)
	jsonbind.RegisterDecode[CreateUserResponse](decodeCreateUserResponseBytes)
	jsonbind.RegisterEncode[CreateUserResponse](encodeCreateUserResponse)
	httpbind.RegisterBind[SearchRequest](bindSearchRequest)
	httpbind.RegisterWrite[SearchRequest](writeSearchRequest)
	jsonbind.RegisterDecode[SearchRequest](decodeSearchRequestBytes)
	jsonbind.RegisterEncode[SearchRequest](encodeSearchRequest)
	httpbind.RegisterBind[SearchResponse](bindSearchResponse)
	httpbind.RegisterWrite[SearchResponse](writeSearchResponse)
	jsonbind.RegisterDecode[SearchResponse](decodeSearchResponseBytes)
	jsonbind.RegisterEncode[SearchResponse](encodeSearchResponse)
}

func decodeCreateUserRequestBytes(data []byte) (CreateUserRequest, error) {
	return decodeCreateUserRequestJSON(json.RawMessage(data))
}

func decodeCreateUserRequestJSON(raw json.RawMessage) (CreateUserRequest, error) {
	var out CreateUserRequest
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["name"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("name", "invalid string", err)
		}
		out.Name = v
	}
	if raw, ok := m["email"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("email", "invalid string", err)
		}
		out.Email = v
	}
	return out, nil
}

func encodeCreateUserRequestMap(v CreateUserRequest) map[string]any {
	body := map[string]any{}
	body["name"] = v.Name
	body["email"] = v.Email
	body["org_id"] = v.OrgID
	body["Authorization"] = v.Token
	return body
}

func encodeCreateUserRequest(w io.Writer, v CreateUserRequest) error {
	return json.NewEncoder(w).Encode(encodeCreateUserRequestMap(v))
}

func bindCreateUserRequest(r *http.Request) (CreateUserRequest, error) {
	var out CreateUserRequest
	var jsonBody map[string]jsonRaw
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbind.IsJSONRequest(r) {
			m, err := httpbind.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbind.IsFormRequest(r) {
			m, err := httpbind.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbind.IsMultipartRequest(r) {
			m, _, err := httpbind.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if qv, ok := httpbind.QueryValue(r, "name"); ok {
		out.Name = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["name"]; ok {
			v, err := jsonbind.DecodeJSONString(raw)
			if err != nil {
				return out, jsonbind.FieldError("name", "invalid string", err)
			}
			out.Name = v
		} else if formBody != nil {
			if fv, ok := formBody["name"]; ok {
				out.Name = fv
			}
		}
	}
	if qv, ok := httpbind.QueryValue(r, "email"); ok {
		out.Email = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["email"]; ok {
			v, err := jsonbind.DecodeJSONString(raw)
			if err != nil {
				return out, jsonbind.FieldError("email", "invalid string", err)
			}
			out.Email = v
		} else if formBody != nil {
			if fv, ok := formBody["email"]; ok {
				out.Email = fv
			}
		}
	}
	out.OrgID = httpbind.PathValue(r, "org_id")
	out.Token = httpbind.HeaderValue(r, "Authorization")
	return out, nil
}

func writeCreateUserRequest(w http.ResponseWriter, r *http.Request, v CreateUserRequest) error {
	_ = r
	return httpbind.WriteJSON(w, http.StatusOK, encodeCreateUserRequestMap(v))
}

func decodeCreateUserResponseBytes(data []byte) (CreateUserResponse, error) {
	return decodeCreateUserResponseJSON(json.RawMessage(data))
}

func decodeCreateUserResponseJSON(raw json.RawMessage) (CreateUserResponse, error) {
	var out CreateUserResponse
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["id"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("iD", "invalid string", err)
		}
		out.ID = v
	}
	if raw, ok := m["name"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("name", "invalid string", err)
		}
		out.Name = v
	}
	if raw, ok := m["email"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("email", "invalid string", err)
		}
		out.Email = v
	}
	return out, nil
}

func encodeCreateUserResponseMap(v CreateUserResponse) map[string]any {
	body := map[string]any{}
	body["id"] = v.ID
	body["name"] = v.Name
	body["email"] = v.Email
	return body
}

func encodeCreateUserResponse(w io.Writer, v CreateUserResponse) error {
	return json.NewEncoder(w).Encode(encodeCreateUserResponseMap(v))
}

func bindCreateUserResponse(r *http.Request) (CreateUserResponse, error) {
	var out CreateUserResponse
	var jsonBody map[string]jsonRaw
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbind.IsJSONRequest(r) {
			m, err := httpbind.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbind.IsFormRequest(r) {
			m, err := httpbind.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbind.IsMultipartRequest(r) {
			m, _, err := httpbind.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if qv, ok := httpbind.QueryValue(r, "iD"); ok {
		out.ID = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["iD"]; ok {
			v, err := jsonbind.DecodeJSONString(raw)
			if err != nil {
				return out, jsonbind.FieldError("iD", "invalid string", err)
			}
			out.ID = v
		} else if formBody != nil {
			if fv, ok := formBody["iD"]; ok {
				out.ID = fv
			}
		}
	}
	if qv, ok := httpbind.QueryValue(r, "name"); ok {
		out.Name = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["name"]; ok {
			v, err := jsonbind.DecodeJSONString(raw)
			if err != nil {
				return out, jsonbind.FieldError("name", "invalid string", err)
			}
			out.Name = v
		} else if formBody != nil {
			if fv, ok := formBody["name"]; ok {
				out.Name = fv
			}
		}
	}
	if qv, ok := httpbind.QueryValue(r, "email"); ok {
		out.Email = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["email"]; ok {
			v, err := jsonbind.DecodeJSONString(raw)
			if err != nil {
				return out, jsonbind.FieldError("email", "invalid string", err)
			}
			out.Email = v
		} else if formBody != nil {
			if fv, ok := formBody["email"]; ok {
				out.Email = fv
			}
		}
	}
	return out, nil
}

func writeCreateUserResponse(w http.ResponseWriter, r *http.Request, v CreateUserResponse) error {
	_ = r
	return httpbind.WriteJSON(w, http.StatusOK, encodeCreateUserResponseMap(v))
}

func decodeSearchRequestBytes(data []byte) (SearchRequest, error) {
	return decodeSearchRequestJSON(json.RawMessage(data))
}

func decodeSearchRequestJSON(raw json.RawMessage) (SearchRequest, error) {
	var out SearchRequest
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["filter"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("filter", "invalid string", err)
		}
		out.Filter = v
	}
	return out, nil
}

func encodeSearchRequestMap(v SearchRequest) map[string]any {
	body := map[string]any{}
	body["keyword"] = v.Keyword
	body["page"] = v.Page
	body["filter"] = v.Filter
	return body
}

func encodeSearchRequest(w io.Writer, v SearchRequest) error {
	return json.NewEncoder(w).Encode(encodeSearchRequestMap(v))
}

func bindSearchRequest(r *http.Request) (SearchRequest, error) {
	var out SearchRequest
	var jsonBody map[string]jsonRaw
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbind.IsJSONRequest(r) {
			m, err := httpbind.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbind.IsFormRequest(r) {
			m, err := httpbind.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbind.IsMultipartRequest(r) {
			m, _, err := httpbind.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if qv, ok := httpbind.QueryValue(r, "keyword"); ok {
		out.Keyword = qv
	}
	if qv, ok := httpbind.QueryValue(r, "page"); ok {
		v, err := httpbind.ParseInt(qv)
		if err != nil {
			return out, httpbind.BindError("page", "query", "invalid int")
		}
		out.Page = v
	}
	if err := readBody(); err != nil {
		return out, err
	}
	if raw, ok := jsonBody["filter"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("filter", "invalid string", err)
		}
		out.Filter = v
	} else if formBody != nil {
		if fv, ok := formBody["filter"]; ok {
			out.Filter = fv
		}
	}
	return out, nil
}

func writeSearchRequest(w http.ResponseWriter, r *http.Request, v SearchRequest) error {
	_ = r
	return httpbind.WriteJSON(w, http.StatusOK, encodeSearchRequestMap(v))
}

func decodeSearchResponseBytes(data []byte) (SearchResponse, error) {
	return decodeSearchResponseJSON(json.RawMessage(data))
}

func decodeSearchResponseJSON(raw json.RawMessage) (SearchResponse, error) {
	var out SearchResponse
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["keyword"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("keyword", "invalid string", err)
		}
		out.Keyword = v
	}
	if raw, ok := m["page"]; ok {
		v, err := jsonbind.DecodeJSONInt(raw)
		if err != nil {
			return out, jsonbind.FieldError("page", "invalid int", err)
		}
		out.Page = v
	}
	if raw, ok := m["filter"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("filter", "invalid string", err)
		}
		out.Filter = v
	}
	return out, nil
}

func encodeSearchResponseMap(v SearchResponse) map[string]any {
	body := map[string]any{}
	body["keyword"] = v.Keyword
	body["page"] = v.Page
	body["filter"] = v.Filter
	return body
}

func encodeSearchResponse(w io.Writer, v SearchResponse) error {
	return json.NewEncoder(w).Encode(encodeSearchResponseMap(v))
}

func bindSearchResponse(r *http.Request) (SearchResponse, error) {
	var out SearchResponse
	var jsonBody map[string]jsonRaw
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbind.IsJSONRequest(r) {
			m, err := httpbind.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbind.IsFormRequest(r) {
			m, err := httpbind.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbind.IsMultipartRequest(r) {
			m, _, err := httpbind.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if qv, ok := httpbind.QueryValue(r, "keyword"); ok {
		out.Keyword = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["keyword"]; ok {
			v, err := jsonbind.DecodeJSONString(raw)
			if err != nil {
				return out, jsonbind.FieldError("keyword", "invalid string", err)
			}
			out.Keyword = v
		} else if formBody != nil {
			if fv, ok := formBody["keyword"]; ok {
				out.Keyword = fv
			}
		}
	}
	if qv, ok := httpbind.QueryValue(r, "page"); ok {
		v, err := httpbind.ParseInt(qv)
		if err != nil {
			return out, httpbind.BindError("page", "query", "invalid int")
		}
		out.Page = v
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["page"]; ok {
			v, err := jsonbind.DecodeJSONInt(raw)
			if err != nil {
				return out, jsonbind.FieldError("page", "invalid int", err)
			}
			out.Page = v
		} else if formBody != nil {
			if fv, ok := formBody["page"]; ok {
				v, err := httpbind.ParseInt(fv)
				if err != nil {
					return out, httpbind.BindError("page", "payload", "invalid int")
				}
				out.Page = v
			}
		}
	}
	if qv, ok := httpbind.QueryValue(r, "filter"); ok {
		out.Filter = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["filter"]; ok {
			v, err := jsonbind.DecodeJSONString(raw)
			if err != nil {
				return out, jsonbind.FieldError("filter", "invalid string", err)
			}
			out.Filter = v
		} else if formBody != nil {
			if fv, ok := formBody["filter"]; ok {
				out.Filter = fv
			}
		}
	}
	return out, nil
}

func writeSearchResponse(w http.ResponseWriter, r *http.Request, v SearchResponse) error {
	_ = r
	return httpbind.WriteJSON(w, http.StatusOK, encodeSearchResponseMap(v))
}
