// Code generated by tinybind; DO NOT EDIT.

package main

import (
	"encoding/json"
	"io"

	"github.com/shibukawa/tinybind-go/jsonbind"
)

func init() {
	jsonbind.RegisterDecode[Note](decodeNoteBytes)
	jsonbind.RegisterEncode[Note](encodeNote)
}

func decodeNoteBytes(data []byte) (Note, error) {
	return decodeNoteJSON(json.RawMessage(data))
}

func decodeNoteJSON(raw json.RawMessage) (Note, error) {
	var out Note
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["text"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("text", "invalid string", err)
		}
		out.Text = v
	}
	if raw, ok := m["n"]; ok {
		v, err := jsonbind.DecodeJSONInt(raw)
		if err != nil {
			return out, jsonbind.FieldError("n", "invalid int", err)
		}
		out.N = v
	}
	return out, nil
}

func encodeNoteMap(v Note) map[string]any {
	body := map[string]any{}
	body["text"] = v.Text
	body["n"] = v.N
	return body
}

func encodeNote(w io.Writer, v Note) error {
	return json.NewEncoder(w).Encode(encodeNoteMap(v))
}
