// Package codegen emits reflection-free configbind apply, flag, and env key tables.
package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"strconv"
	"strings"

	"github.com/shibukawa/tinybind-go/cliparser"
	"github.com/shibukawa/tinybind-go/configbind"
	"github.com/shibukawa/tinybind-go/minitoml/codegen"
)

// Spec is a Bind-style struct with prefix for generation.
// Reuses minitoml/codegen field shapes.
type Spec = codegen.Spec

// Field and FieldKind re-export for callers.
type (
	Field     = codegen.Field
	FieldKind = codegen.FieldKind
)

const (
	FieldString      = codegen.FieldString
	FieldBool        = codegen.FieldBool
	FieldInt         = codegen.FieldInt
	FieldStringSlice = codegen.FieldStringSlice
	FieldStruct      = codegen.FieldStruct

	// ScaffoldTOMLName and ScaffoldEnvName are the exported constant names
	// emitted into the package containing Bind calls.
	ScaffoldTOMLName = "ConfigbindScaffoldTOML"
	ScaffoldEnvName  = "ConfigbindScaffoldEnv"
)

// Generate emits package source that registers Meta and Apply for each Spec.
func Generate(packageName string, specs []Spec) ([]byte, error) {
	if packageName == "" {
		return nil, fmt.Errorf("configbind/codegen: package name required")
	}
	if len(specs) == 0 {
		return nil, fmt.Errorf("configbind/codegen: no specs")
	}
	tomlScaffold, envScaffold, err := GenerateScaffolds(specs)
	if err != nil {
		return nil, err
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by configbind/codegen; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", packageName)
	b.WriteString("import (\n")
	b.WriteString("\t\"fmt\"\n")
	b.WriteString("\t\"strconv\"\n\n")
	b.WriteString("\t\"github.com/shibukawa/tinybind-go/cliparser\"\n")
	b.WriteString("\t\"github.com/shibukawa/tinybind-go/configbind\"\n")
	b.WriteString(")\n\n")

	fmt.Fprintf(&b, "// %s is a sample TOML configuration derived from Bind struct metadata.\n", ScaffoldTOMLName)
	fmt.Fprintf(&b, "const %s = %s\n\n", ScaffoldTOMLName, strconv.Quote(tomlScaffold))
	fmt.Fprintf(&b, "// %s is a sample .env file derived from Bind struct metadata.\n", ScaffoldEnvName)
	fmt.Fprintf(&b, "const %s = %s\n\n", ScaffoldEnvName, strconv.Quote(envScaffold))

	b.WriteString("func init() {\n")
	for _, s := range specs {
		fmt.Fprintf(&b, "\tregister%s()\n", s.TypeName)
	}
	b.WriteString("}\n\n")

	for _, s := range specs {
		if err := emitType(&b, s); err != nil {
			return nil, err
		}
	}

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return b.Bytes(), fmt.Errorf("configbind/codegen: format: %w\n%s", err, b.String())
	}
	return formatted, nil
}

// GenerateScaffolds builds TOML and .env sample text from Bind struct metadata.
// It does not write files or generate an application command; callers may print
// the emitted constants from a command appropriate for their application.
func GenerateScaffolds(specs []Spec) (tomlText, envText string, err error) {
	if len(specs) == 0 {
		return "", "", fmt.Errorf("configbind/codegen: no specs")
	}

	var toml, env bytes.Buffer
	var allMetas []cliparser.FieldMeta
	var leaves []Field
	seenPrefixes := make(map[string]string, len(specs))
	for specIndex, s := range specs {
		if s.TypeName == "" || s.Prefix == "" {
			return "", "", fmt.Errorf("configbind/codegen: TypeName and Prefix required")
		}
		if !validBareKeyPath(s.Prefix) {
			return "", "", fmt.Errorf("configbind/codegen: %s: prefix %q is not a bare TOML key path", s.TypeName, s.Prefix)
		}
		if previous, ok := seenPrefixes[s.Prefix]; ok {
			return "", "", fmt.Errorf("configbind/codegen: duplicate prefix %q for %s and %s", s.Prefix, previous, s.TypeName)
		}
		seenPrefixes[s.Prefix] = s.TypeName

		if specIndex > 0 {
			toml.WriteByte('\n')
		}
		fmt.Fprintf(&toml, "[%s]\n", s.Prefix)
		if err := emitTOMLScaffoldFields(&toml, "", s.Fields); err != nil {
			return "", "", fmt.Errorf("configbind/codegen: %s: %w", s.TypeName, err)
		}

		metas := collectFlagMetas(s.Prefix, s.Fields)
		allMetas = append(allMetas, metas...)
		leaves = appendLeafFields(leaves, s.Fields)
	}

	defs, err := cliparser.BuildDefs(allMetas)
	if err != nil {
		return "", "", fmt.Errorf("configbind/codegen: scaffold: %w", err)
	}
	for i, def := range defs {
		name := def.Env
		if name == "-" {
			continue
		}
		if name == "" && len(def.Longs) > 0 {
			name = configbind.EnvName(def.Longs[0])
		}
		if name == "" {
			continue
		}
		writeScaffoldHelp(&env, def.Help)
		value, err := scaffoldValue(leaves[i], false)
		if err != nil {
			return "", "", fmt.Errorf("configbind/codegen: %s: %w", def.ConfigKey, err)
		}
		fmt.Fprintf(&env, "%s=%s\n", name, value)
	}
	return toml.String(), env.String(), nil
}

func emitTOMLScaffoldFields(b *bytes.Buffer, prefix string, fields []Field) error {
	for _, f := range fields {
		if f.Key == "" || !validBareKeyPath(f.Key) {
			return fmt.Errorf("field %s has invalid bare TOML key %q", f.GoName, f.Key)
		}
		key := joinKey(prefix, f.Key)
		if f.Kind == FieldStruct {
			if err := emitTOMLScaffoldFields(b, key, f.Nested); err != nil {
				return err
			}
			continue
		}
		writeScaffoldHelp(b, f.Help)
		value, err := scaffoldValue(f, true)
		if err != nil {
			return fmt.Errorf("field %s: %w", f.GoName, err)
		}
		fmt.Fprintf(b, "%s = %s\n", key, value)
	}
	return nil
}

func appendLeafFields(dst []Field, fields []Field) []Field {
	for _, f := range fields {
		if f.Kind == FieldStruct {
			dst = appendLeafFields(dst, f.Nested)
			continue
		}
		dst = append(dst, f)
	}
	return dst
}

func scaffoldValue(f Field, toml bool) (string, error) {
	switch f.Kind {
	case FieldString:
		if toml {
			return quoteTOMLString(f.Default), nil
		}
		return strconv.Quote(f.Default), nil
	case FieldBool:
		if f.Default == "" {
			return "false", nil
		}
		value, err := strconv.ParseBool(f.Default)
		if err != nil {
			return "", fmt.Errorf("invalid bool default %q", f.Default)
		}
		return strconv.FormatBool(value), nil
	case FieldInt:
		if f.Default == "" {
			return "0", nil
		}
		value, err := strconv.ParseInt(f.Default, 10, 64)
		if err != nil {
			return "", fmt.Errorf("invalid int default %q", f.Default)
		}
		return strconv.FormatInt(value, 10), nil
	case FieldStringSlice:
		if toml {
			return "[]", nil
		}
		return strconv.Quote(""), nil
	default:
		return "", fmt.Errorf("unsupported field kind for %s", f.GoName)
	}
}

func writeScaffoldHelp(b *bytes.Buffer, help string) {
	for _, line := range strings.Split(strings.TrimSpace(help), "\n") {
		if line != "" {
			fmt.Fprintf(b, "# %s\n", strings.TrimSpace(line))
		}
	}
}

func quoteTOMLString(value string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range value {
		switch r {
		case '"', '\\':
			b.WriteByte('\\')
			b.WriteRune(r)
		case '\b':
			b.WriteString("\\b")
		case '\t':
			b.WriteString("\\t")
		case '\n':
			b.WriteString("\\n")
		case '\f':
			b.WriteString("\\f")
		case '\r':
			b.WriteString("\\r")
		default:
			if r < 0x20 || r == 0x7f {
				fmt.Fprintf(&b, "\\u%04X", r)
			} else {
				b.WriteRune(r)
			}
		}
	}
	b.WriteByte('"')
	return b.String()
}

func validBareKeyPath(path string) bool {
	for _, part := range strings.Split(path, ".") {
		if part == "" {
			return false
		}
		for _, r := range part {
			if !((r >= 'A' && r <= 'Z') || (r >= 'a' && r <= 'z') ||
				(r >= '0' && r <= '9') || r == '_' || r == '-') {
				return false
			}
		}
	}
	return true
}

func emitType(b *bytes.Buffer, s Spec) error {
	if s.TypeName == "" || s.Prefix == "" {
		return fmt.Errorf("configbind/codegen: TypeName and Prefix required")
	}
	keys := collectKeys(s.Prefix, s.Fields)
	defaults := collectDefaults(s.Prefix, s.Fields)
	flagMetas := collectFlagMetas(s.Prefix, s.Fields)
	if _, err := cliparser.BuildDefs(flagMetas); err != nil {
		return fmt.Errorf("configbind/codegen: %s: %w", s.TypeName, err)
	}

	fmt.Fprintf(b, "func register%s() {\n", s.TypeName)
	b.WriteString("\tconfigbind.RegisterType[")
	b.WriteString(s.TypeName)
	b.WriteString("](")
	fmt.Fprintf(b, "%s, configbind.Meta{\n", strconv.Quote(s.TypeName))
	fmt.Fprintf(b, "\t\tTypeName: %s,\n", strconv.Quote(s.TypeName))
	b.WriteString("\t\tKnownKeys: []string{\n")
	for _, k := range keys {
		fmt.Fprintf(b, "\t\t\t%s,\n", strconv.Quote(k))
	}
	b.WriteString("\t\t},\n")
	if len(defaults) > 0 {
		b.WriteString("\t\tDefaults: map[string]string{\n")
		// stable order
		for _, k := range keys {
			if v, ok := defaults[k]; ok {
				fmt.Fprintf(b, "\t\t\t%s: %s,\n", strconv.Quote(k), strconv.Quote(v))
			}
		}
		b.WriteString("\t\t},\n")
	}
	b.WriteString("\t\tFlagMetas: []cliparser.FieldMeta{\n")
	for _, m := range flagMetas {
		fmt.Fprintf(b, "\t\t\t{Prefix: %s, Key: %s", strconv.Quote(m.Prefix), strconv.Quote(m.Key))
		if m.Opt != "" {
			fmt.Fprintf(b, ", Opt: %s", strconv.Quote(m.Opt))
		}
		if m.Env != "" {
			fmt.Fprintf(b, ", Env: %s", strconv.Quote(m.Env))
		}
		if m.Help != "" {
			fmt.Fprintf(b, ", Help: %s", strconv.Quote(m.Help))
		}
		switch m.Kind {
		case cliparser.KindBool:
			b.WriteString(", Kind: cliparser.KindBool")
		case cliparser.KindArray:
			b.WriteString(", Kind: cliparser.KindArray")
		}
		b.WriteString("},\n")
	}
	b.WriteString("\t\t},\n")
	fmt.Fprintf(b, "\t\tApply: apply%s,\n", s.TypeName)
	b.WriteString("\t})\n")
	b.WriteString("}\n\n")

	// Apply function
	fmt.Fprintf(b, "func apply%s(dst any, o *configbind.Overlay) error {\n", s.TypeName)
	fmt.Fprintf(b, "\tp, ok := dst.(*%s)\n", s.TypeName)
	b.WriteString("\tif !ok || p == nil {\n")
	fmt.Fprintf(b, "\t\treturn fmt.Errorf(\"configbind: apply %s: bad destination\")\n", s.TypeName)
	b.WriteString("\t}\n")
	if err := emitApplyFields(b, "p", s.Prefix, s.Fields); err != nil {
		return err
	}
	b.WriteString("\treturn nil\n")
	b.WriteString("}\n\n")
	return nil
}

func emitApplyFields(b *bytes.Buffer, recv, prefix string, fields []Field) error {
	for _, f := range fields {
		full := joinKey(prefix, f.Key)
		access := recv + "." + f.GoName
		switch f.Kind {
		case FieldString:
			fmt.Fprintf(b, "\tif v, ok := o.GetString(%q); ok {\n", full)
			fmt.Fprintf(b, "\t\t%s = v\n", access)
			if f.Default != "" {
				b.WriteString("\t} else {\n")
				fmt.Fprintf(b, "\t\t%s = %s\n", access, strconv.Quote(f.Default))
				b.WriteString("\t}\n")
			} else {
				b.WriteString("\t}\n")
			}
		case FieldBool:
			fmt.Fprintf(b, "\tif v, ok := o.GetString(%q); ok {\n", full)
			b.WriteString("\t\tbb, err := strconv.ParseBool(v)\n")
			b.WriteString("\t\tif err != nil {\n")
			fmt.Fprintf(b, "\t\t\treturn fmt.Errorf(\"configbind: %s: %%w\", err)\n", full)
			b.WriteString("\t\t}\n")
			fmt.Fprintf(b, "\t\t%s = bb\n", access)
			if f.Default != "" {
				value, err := strconv.ParseBool(f.Default)
				if err != nil {
					return fmt.Errorf("invalid bool default %q for %s", f.Default, f.GoName)
				}
				b.WriteString("\t} else {\n")
				fmt.Fprintf(b, "\t\t%s = %v\n", access, value)
				b.WriteString("\t}\n")
			} else {
				b.WriteString("\t}\n")
			}
		case FieldInt:
			fmt.Fprintf(b, "\tif v, ok := o.GetString(%q); ok {\n", full)
			b.WriteString("\t\tn, err := strconv.ParseInt(v, 10, 64)\n")
			b.WriteString("\t\tif err != nil {\n")
			fmt.Fprintf(b, "\t\t\treturn fmt.Errorf(\"configbind: %s: %%w\", err)\n", full)
			b.WriteString("\t\t}\n")
			fmt.Fprintf(b, "\t\t%s = int(n)\n", access)
			if f.Default != "" {
				value, err := strconv.ParseInt(f.Default, 10, 64)
				if err != nil {
					return fmt.Errorf("invalid int default %q for %s", f.Default, f.GoName)
				}
				b.WriteString("\t} else {\n")
				fmt.Fprintf(b, "\t\t%s = %s\n", access, strconv.FormatInt(value, 10))
				b.WriteString("\t}\n")
			} else {
				b.WriteString("\t}\n")
			}
		case FieldStringSlice:
			fmt.Fprintf(b, "\tif v, ok := o.GetMulti(%q); ok {\n", full)
			fmt.Fprintf(b, "\t\t%s = v\n", access)
			b.WriteString("\t}\n")
		case FieldStruct:
			if err := emitApplyFields(b, access, full, f.Nested); err != nil {
				return err
			}
		default:
			return fmt.Errorf("unsupported field kind for %s", f.GoName)
		}
	}
	return nil
}

func collectKeys(prefix string, fields []Field) []string {
	var keys []string
	var walk func(string, []Field)
	walk = func(p string, fs []Field) {
		for _, f := range fs {
			full := joinKey(p, f.Key)
			if f.Kind == FieldStruct {
				walk(full, f.Nested)
				continue
			}
			keys = append(keys, full)
		}
	}
	walk(prefix, fields)
	return keys
}

func collectDefaults(prefix string, fields []Field) map[string]string {
	out := map[string]string{}
	var walk func(string, []Field)
	walk = func(p string, fs []Field) {
		for _, f := range fs {
			full := joinKey(p, f.Key)
			if f.Kind == FieldStruct {
				walk(full, f.Nested)
				continue
			}
			if f.Default != "" {
				out[full] = f.Default
			}
		}
	}
	walk(prefix, fields)
	return out
}

func collectFlagMetas(prefix string, fields []Field) []cliparser.FieldMeta {
	var out []cliparser.FieldMeta
	var walk func(string, []Field)
	walk = func(p string, fs []Field) {
		for _, f := range fs {
			full := joinKey(p, f.Key)
			// relative key under original prefix for cliparser FieldMeta
			rel := strings.TrimPrefix(full, prefix+".")
			if full == prefix {
				rel = ""
			}
			if f.Kind == FieldStruct {
				walk(full, f.Nested)
				continue
			}
			// FieldMeta uses Prefix + Key where Key is relative path under prefix
			key := strings.TrimPrefix(full, prefix+".")
			m := cliparser.FieldMeta{
				Prefix: prefix,
				Key:    key,
				Opt:    f.Opt,
				Env:    f.Env,
				Help:   f.Help,
			}
			switch f.Kind {
			case FieldBool:
				m.Kind = cliparser.KindBool
			case FieldStringSlice:
				m.Kind = cliparser.KindArray
			default:
				m.Kind = cliparser.KindString
			}
			_ = rel
			out = append(out, m)
		}
	}
	walk(prefix, fields)
	return out
}

func joinKey(prefix, key string) string {
	if prefix == "" {
		return key
	}
	if key == "" {
		return prefix
	}
	return prefix + "." + key
}
