// Code generated by configbind/codegen; DO NOT EDIT.

package main

import (
	"fmt"
	"strconv"

	"github.com/shibukawa/tinybind-go/cliparser"
	"github.com/shibukawa/tinybind-go/configbind"
)

func init() {
	registerServerConfig()
}

func registerServerConfig() {
	configbind.RegisterType[ServerConfig]("ServerConfig", configbind.Meta{
		TypeName: "ServerConfig",
		KnownKeys: []string{
			"server.port",
		},
		Defaults: map[string]string{
			"server.port": "8080",
		},
		FlagMetas: []cliparser.FieldMeta{
			{Prefix: "server", Key: "port", Opt: "port,p", Help: "HTTP listen port"},
		},
		Apply: applyServerConfig,
	})
}

func applyServerConfig(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*ServerConfig)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply ServerConfig: bad destination")
	}
	if v, ok := o.GetString("server.port"); ok {
		n, err := strconv.ParseInt(v, 10, 64)
		if err != nil {
			return fmt.Errorf("configbind: server.port: %w", err)
		}
		p.Port = int(n)
	} else {
		p.Port = 8080
	}
	return nil
}
