// Code generated by httpbinder; DO NOT EDIT.

package main

import (
	"encoding/json"
	"io"
	"net/http"

	"github.com/shibukawa/httpbind-go"
)

type jsonRaw = json.RawMessage

func init() {
	httpbinder.RegisterBind[CreateUserRequest](bindCreateUserRequest)
	httpbinder.RegisterWrite[CreateUserRequest](writeCreateUserRequest)
	httpbinder.RegisterDecode[CreateUserRequest](decodeCreateUserRequestBytes)
	httpbinder.RegisterEncode[CreateUserRequest](encodeCreateUserRequest)
	httpbinder.RegisterBind[CreateUserResponse](bindCreateUserResponse)
	httpbinder.RegisterWrite[CreateUserResponse](writeCreateUserResponse)
	httpbinder.RegisterDecode[CreateUserResponse](decodeCreateUserResponseBytes)
	httpbinder.RegisterEncode[CreateUserResponse](encodeCreateUserResponse)
	httpbinder.RegisterBind[SearchRequest](bindSearchRequest)
	httpbinder.RegisterWrite[SearchRequest](writeSearchRequest)
	httpbinder.RegisterDecode[SearchRequest](decodeSearchRequestBytes)
	httpbinder.RegisterEncode[SearchRequest](encodeSearchRequest)
	httpbinder.RegisterBind[SearchResponse](bindSearchResponse)
	httpbinder.RegisterWrite[SearchResponse](writeSearchResponse)
	httpbinder.RegisterDecode[SearchResponse](decodeSearchResponseBytes)
	httpbinder.RegisterEncode[SearchResponse](encodeSearchResponse)
	httpbinder.RegisterBind[EchoRequest](bindEchoRequest)
	httpbinder.RegisterWrite[EchoRequest](writeEchoRequest)
	httpbinder.RegisterDecode[EchoRequest](decodeEchoRequestBytes)
	httpbinder.RegisterEncode[EchoRequest](encodeEchoRequest)
	httpbinder.RegisterBind[EchoResponse](bindEchoResponse)
	httpbinder.RegisterWrite[EchoResponse](writeEchoResponse)
	httpbinder.RegisterDecode[EchoResponse](decodeEchoResponseBytes)
	httpbinder.RegisterEncode[EchoResponse](encodeEchoResponse)
	httpbinder.RegisterBind[SessionRequest](bindSessionRequest)
	httpbinder.RegisterWrite[SessionRequest](writeSessionRequest)
	httpbinder.RegisterDecode[SessionRequest](decodeSessionRequestBytes)
	httpbinder.RegisterEncode[SessionRequest](encodeSessionRequest)
	httpbinder.RegisterBind[SessionResponse](bindSessionResponse)
	httpbinder.RegisterWrite[SessionResponse](writeSessionResponse)
	httpbinder.RegisterDecode[SessionResponse](decodeSessionResponseBytes)
	httpbinder.RegisterEncode[SessionResponse](encodeSessionResponse)
	httpbinder.RegisterBind[UserGetRequest](bindUserGetRequest)
	httpbinder.RegisterWrite[UserGetRequest](writeUserGetRequest)
	httpbinder.RegisterDecode[UserGetRequest](decodeUserGetRequestBytes)
	httpbinder.RegisterEncode[UserGetRequest](encodeUserGetRequest)
	httpbinder.RegisterBind[UserGetResponse](bindUserGetResponse)
	httpbinder.RegisterWrite[UserGetResponse](writeUserGetResponse)
	httpbinder.RegisterDecode[UserGetResponse](decodeUserGetResponseBytes)
	httpbinder.RegisterEncode[UserGetResponse](encodeUserGetResponse)
	httpbinder.RegisterBind[ChatRequest](bindChatRequest)
	httpbinder.RegisterWrite[ChatRequest](writeChatRequest)
	httpbinder.RegisterDecode[ChatRequest](decodeChatRequestBytes)
	httpbinder.RegisterEncode[ChatRequest](encodeChatRequest)
	httpbinder.RegisterBind[ChatEvent](bindChatEvent)
	httpbinder.RegisterWrite[ChatEvent](writeChatEvent)
	httpbinder.RegisterDecode[ChatEvent](decodeChatEventBytes)
	httpbinder.RegisterEncode[ChatEvent](encodeChatEvent)
	httpbinder.RegisterBind[HealthResponse](bindHealthResponse)
	httpbinder.RegisterWrite[HealthResponse](writeHealthResponse)
	httpbinder.RegisterDecode[HealthResponse](decodeHealthResponseBytes)
	httpbinder.RegisterEncode[HealthResponse](encodeHealthResponse)
}

func decodeCreateUserRequestBytes(data []byte) (CreateUserRequest, error) {
	return decodeCreateUserRequestJSON(json.RawMessage(data))
}

func decodeCreateUserRequestJSON(raw json.RawMessage) (CreateUserRequest, error) {
	var out CreateUserRequest
	m, err := httpbinder.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["name"]; ok {
		v, err := httpbinder.DecodeJSONString(raw)
		if err != nil {
			return out, httpbinder.BindError("name", "payload", "invalid string")
		}
		out.Name = v
	}
	if raw, ok := m["email"]; ok {
		v, err := httpbinder.DecodeJSONString(raw)
		if err != nil {
			return out, httpbinder.BindError("email", "payload", "invalid string")
		}
		out.Email = v
	}
	return out, nil
}

func encodeCreateUserRequestMap(v CreateUserRequest) map[string]any {
	body := map[string]any{}
	body["name"] = v.Name
	body["email"] = v.Email
	body["org_id"] = v.OrgID
	body["Authorization"] = v.Token
	return body
}

func encodeCreateUserRequest(w io.Writer, v CreateUserRequest) error {
	return json.NewEncoder(w).Encode(encodeCreateUserRequestMap(v))
}

func bindCreateUserRequest(r *http.Request) (CreateUserRequest, error) {
	var out CreateUserRequest
	var jsonBody map[string]jsonRaw
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbinder.IsJSONRequest(r) {
			m, err := httpbinder.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbinder.IsFormRequest(r) {
			m, err := httpbinder.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbinder.IsMultipartRequest(r) {
			m, _, err := httpbinder.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if qv, ok := httpbinder.QueryValue(r, "name"); ok {
		out.Name = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["name"]; ok {
			v, err := httpbinder.DecodeJSONString(raw)
			if err != nil {
				return out, httpbinder.BindError("name", "payload", "invalid string")
			}
			out.Name = v
		} else if formBody != nil {
			if fv, ok := formBody["name"]; ok {
				out.Name = fv
			}
		}
	}
	if qv, ok := httpbinder.QueryValue(r, "email"); ok {
		out.Email = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["email"]; ok {
			v, err := httpbinder.DecodeJSONString(raw)
			if err != nil {
				return out, httpbinder.BindError("email", "payload", "invalid string")
			}
			out.Email = v
		} else if formBody != nil {
			if fv, ok := formBody["email"]; ok {
				out.Email = fv
			}
		}
	}
	out.OrgID = httpbinder.PathValue(r, "org_id")
	out.Token = httpbinder.HeaderValue(r, "Authorization")
	return out, nil
}

func writeCreateUserRequest(w http.ResponseWriter, r *http.Request, v CreateUserRequest) error {
	_ = r
	return httpbinder.WriteJSON(w, http.StatusOK, encodeCreateUserRequestMap(v))
}

func decodeCreateUserResponseBytes(data []byte) (CreateUserResponse, error) {
	return decodeCreateUserResponseJSON(json.RawMessage(data))
}

func decodeCreateUserResponseJSON(raw json.RawMessage) (CreateUserResponse, error) {
	var out CreateUserResponse
	m, err := httpbinder.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["id"]; ok {
		v, err := httpbinder.DecodeJSONString(raw)
		if err != nil {
			return out, httpbinder.BindError("iD", "payload", "invalid string")
		}
		out.ID = v
	}
	if raw, ok := m["name"]; ok {
		v, err := httpbinder.DecodeJSONString(raw)
		if err != nil {
			return out, httpbinder.BindError("name", "payload", "invalid string")
		}
		out.Name = v
	}
	if raw, ok := m["email"]; ok {
		v, err := httpbinder.DecodeJSONString(raw)
		if err != nil {
			return out, httpbinder.BindError("email", "payload", "invalid string")
		}
		out.Email = v
	}
	if raw, ok := m["org_id"]; ok {
		v, err := httpbinder.DecodeJSONString(raw)
		if err != nil {
			return out, httpbinder.BindError("orgID", "payload", "invalid string")
		}
		out.OrgID = v
	}
	return out, nil
}

func encodeCreateUserResponseMap(v CreateUserResponse) map[string]any {
	body := map[string]any{}
	body["id"] = v.ID
	body["name"] = v.Name
	body["email"] = v.Email
	body["org_id"] = v.OrgID
	return body
}

func encodeCreateUserResponse(w io.Writer, v CreateUserResponse) error {
	return json.NewEncoder(w).Encode(encodeCreateUserResponseMap(v))
}

func bindCreateUserResponse(r *http.Request) (CreateUserResponse, error) {
	var out CreateUserResponse
	var jsonBody map[string]jsonRaw
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbinder.IsJSONRequest(r) {
			m, err := httpbinder.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbinder.IsFormRequest(r) {
			m, err := httpbinder.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbinder.IsMultipartRequest(r) {
			m, _, err := httpbinder.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if qv, ok := httpbinder.QueryValue(r, "iD"); ok {
		out.ID = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["iD"]; ok {
			v, err := httpbinder.DecodeJSONString(raw)
			if err != nil {
				return out, httpbinder.BindError("iD", "payload", "invalid string")
			}
			out.ID = v
		} else if formBody != nil {
			if fv, ok := formBody["iD"]; ok {
				out.ID = fv
			}
		}
	}
	if qv, ok := httpbinder.QueryValue(r, "name"); ok {
		out.Name = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["name"]; ok {
			v, err := httpbinder.DecodeJSONString(raw)
			if err != nil {
				return out, httpbinder.BindError("name", "payload", "invalid string")
			}
			out.Name = v
		} else if formBody != nil {
			if fv, ok := formBody["name"]; ok {
				out.Name = fv
			}
		}
	}
	if qv, ok := httpbinder.QueryValue(r, "email"); ok {
		out.Email = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["email"]; ok {
			v, err := httpbinder.DecodeJSONString(raw)
			if err != nil {
				return out, httpbinder.BindError("email", "payload", "invalid string")
			}
			out.Email = v
		} else if formBody != nil {
			if fv, ok := formBody["email"]; ok {
				out.Email = fv
			}
		}
	}
	if qv, ok := httpbinder.QueryValue(r, "orgID"); ok {
		out.OrgID = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["orgID"]; ok {
			v, err := httpbinder.DecodeJSONString(raw)
			if err != nil {
				return out, httpbinder.BindError("orgID", "payload", "invalid string")
			}
			out.OrgID = v
		} else if formBody != nil {
			if fv, ok := formBody["orgID"]; ok {
				out.OrgID = fv
			}
		}
	}
	return out, nil
}

func writeCreateUserResponse(w http.ResponseWriter, r *http.Request, v CreateUserResponse) error {
	_ = r
	return httpbinder.WriteJSON(w, http.StatusOK, encodeCreateUserResponseMap(v))
}

func decodeSearchRequestBytes(data []byte) (SearchRequest, error) {
	return decodeSearchRequestJSON(json.RawMessage(data))
}

func decodeSearchRequestJSON(raw json.RawMessage) (SearchRequest, error) {
	var out SearchRequest
	m, err := httpbinder.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["filter"]; ok {
		v, err := httpbinder.DecodeJSONString(raw)
		if err != nil {
			return out, httpbinder.BindError("filter", "payload", "invalid string")
		}
		out.Filter = v
	}
	return out, nil
}

func encodeSearchRequestMap(v SearchRequest) map[string]any {
	body := map[string]any{}
	body["keyword"] = v.Keyword
	body["page"] = v.Page
	body["filter"] = v.Filter
	return body
}

func encodeSearchRequest(w io.Writer, v SearchRequest) error {
	return json.NewEncoder(w).Encode(encodeSearchRequestMap(v))
}

func bindSearchRequest(r *http.Request) (SearchRequest, error) {
	var out SearchRequest
	var jsonBody map[string]jsonRaw
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbinder.IsJSONRequest(r) {
			m, err := httpbinder.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbinder.IsFormRequest(r) {
			m, err := httpbinder.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbinder.IsMultipartRequest(r) {
			m, _, err := httpbinder.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if qv, ok := httpbinder.QueryValue(r, "keyword"); ok {
		out.Keyword = qv
	}
	if qv, ok := httpbinder.QueryValue(r, "page"); ok {
		v, err := httpbinder.ParseInt(qv)
		if err != nil {
			return out, httpbinder.BindError("page", "query", "invalid int")
		}
		out.Page = v
	}
	if err := readBody(); err != nil {
		return out, err
	}
	if raw, ok := jsonBody["filter"]; ok {
		v, err := httpbinder.DecodeJSONString(raw)
		if err != nil {
			return out, httpbinder.BindError("filter", "payload", "invalid string")
		}
		out.Filter = v
	} else if formBody != nil {
		if fv, ok := formBody["filter"]; ok {
			out.Filter = fv
		}
	}
	return out, nil
}

func writeSearchRequest(w http.ResponseWriter, r *http.Request, v SearchRequest) error {
	_ = r
	return httpbinder.WriteJSON(w, http.StatusOK, encodeSearchRequestMap(v))
}

func decodeSearchResponseBytes(data []byte) (SearchResponse, error) {
	return decodeSearchResponseJSON(json.RawMessage(data))
}

func decodeSearchResponseJSON(raw json.RawMessage) (SearchResponse, error) {
	var out SearchResponse
	m, err := httpbinder.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["keyword"]; ok {
		v, err := httpbinder.DecodeJSONString(raw)
		if err != nil {
			return out, httpbinder.BindError("keyword", "payload", "invalid string")
		}
		out.Keyword = v
	}
	if raw, ok := m["page"]; ok {
		v, err := httpbinder.DecodeJSONInt(raw)
		if err != nil {
			return out, httpbinder.BindError("page", "payload", "invalid int")
		}
		out.Page = v
	}
	if raw, ok := m["filter"]; ok {
		v, err := httpbinder.DecodeJSONString(raw)
		if err != nil {
			return out, httpbinder.BindError("filter", "payload", "invalid string")
		}
		out.Filter = v
	}
	if raw, ok := m["hits"]; ok {
		v, err := httpbinder.DecodeJSONInt(raw)
		if err != nil {
			return out, httpbinder.BindError("hits", "payload", "invalid int")
		}
		out.Hits = v
	}
	return out, nil
}

func encodeSearchResponseMap(v SearchResponse) map[string]any {
	body := map[string]any{}
	body["keyword"] = v.Keyword
	body["page"] = v.Page
	body["filter"] = v.Filter
	body["hits"] = v.Hits
	return body
}

func encodeSearchResponse(w io.Writer, v SearchResponse) error {
	return json.NewEncoder(w).Encode(encodeSearchResponseMap(v))
}

func bindSearchResponse(r *http.Request) (SearchResponse, error) {
	var out SearchResponse
	var jsonBody map[string]jsonRaw
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbinder.IsJSONRequest(r) {
			m, err := httpbinder.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbinder.IsFormRequest(r) {
			m, err := httpbinder.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbinder.IsMultipartRequest(r) {
			m, _, err := httpbinder.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if qv, ok := httpbinder.QueryValue(r, "keyword"); ok {
		out.Keyword = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["keyword"]; ok {
			v, err := httpbinder.DecodeJSONString(raw)
			if err != nil {
				return out, httpbinder.BindError("keyword", "payload", "invalid string")
			}
			out.Keyword = v
		} else if formBody != nil {
			if fv, ok := formBody["keyword"]; ok {
				out.Keyword = fv
			}
		}
	}
	if qv, ok := httpbinder.QueryValue(r, "page"); ok {
		v, err := httpbinder.ParseInt(qv)
		if err != nil {
			return out, httpbinder.BindError("page", "query", "invalid int")
		}
		out.Page = v
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["page"]; ok {
			v, err := httpbinder.DecodeJSONInt(raw)
			if err != nil {
				return out, httpbinder.BindError("page", "payload", "invalid int")
			}
			out.Page = v
		} else if formBody != nil {
			if fv, ok := formBody["page"]; ok {
				v, err := httpbinder.ParseInt(fv)
				if err != nil {
					return out, httpbinder.BindError("page", "payload", "invalid int")
				}
				out.Page = v
			}
		}
	}
	if qv, ok := httpbinder.QueryValue(r, "filter"); ok {
		out.Filter = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["filter"]; ok {
			v, err := httpbinder.DecodeJSONString(raw)
			if err != nil {
				return out, httpbinder.BindError("filter", "payload", "invalid string")
			}
			out.Filter = v
		} else if formBody != nil {
			if fv, ok := formBody["filter"]; ok {
				out.Filter = fv
			}
		}
	}
	if qv, ok := httpbinder.QueryValue(r, "hits"); ok {
		v, err := httpbinder.ParseInt(qv)
		if err != nil {
			return out, httpbinder.BindError("hits", "query", "invalid int")
		}
		out.Hits = v
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["hits"]; ok {
			v, err := httpbinder.DecodeJSONInt(raw)
			if err != nil {
				return out, httpbinder.BindError("hits", "payload", "invalid int")
			}
			out.Hits = v
		} else if formBody != nil {
			if fv, ok := formBody["hits"]; ok {
				v, err := httpbinder.ParseInt(fv)
				if err != nil {
					return out, httpbinder.BindError("hits", "payload", "invalid int")
				}
				out.Hits = v
			}
		}
	}
	return out, nil
}

func writeSearchResponse(w http.ResponseWriter, r *http.Request, v SearchResponse) error {
	_ = r
	return httpbinder.WriteJSON(w, http.StatusOK, encodeSearchResponseMap(v))
}

func decodeEchoRequestBytes(data []byte) (EchoRequest, error) {
	return decodeEchoRequestJSON(json.RawMessage(data))
}

func decodeEchoRequestJSON(raw json.RawMessage) (EchoRequest, error) {
	var out EchoRequest
	m, err := httpbinder.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["message"]; ok {
		v, err := httpbinder.DecodeJSONString(raw)
		if err != nil {
			return out, httpbinder.BindError("message", "payload", "invalid string")
		}
		out.Message = v
	}
	return out, nil
}

func encodeEchoRequestMap(v EchoRequest) map[string]any {
	body := map[string]any{}
	body["message"] = v.Message
	body["n"] = v.N
	return body
}

func encodeEchoRequest(w io.Writer, v EchoRequest) error {
	return json.NewEncoder(w).Encode(encodeEchoRequestMap(v))
}

func bindEchoRequest(r *http.Request) (EchoRequest, error) {
	var out EchoRequest
	var jsonBody map[string]jsonRaw
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbinder.IsJSONRequest(r) {
			m, err := httpbinder.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbinder.IsFormRequest(r) {
			m, err := httpbinder.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbinder.IsMultipartRequest(r) {
			m, _, err := httpbinder.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if qv, ok := httpbinder.QueryValue(r, "message"); ok {
		out.Message = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["message"]; ok {
			v, err := httpbinder.DecodeJSONString(raw)
			if err != nil {
				return out, httpbinder.BindError("message", "payload", "invalid string")
			}
			out.Message = v
		} else if formBody != nil {
			if fv, ok := formBody["message"]; ok {
				out.Message = fv
			}
		}
	}
	if qv, ok := httpbinder.QueryValue(r, "n"); ok {
		v, err := httpbinder.ParseInt(qv)
		if err != nil {
			return out, httpbinder.BindError("n", "query", "invalid int")
		}
		out.N = v
	}
	return out, nil
}

func writeEchoRequest(w http.ResponseWriter, r *http.Request, v EchoRequest) error {
	_ = r
	return httpbinder.WriteJSON(w, http.StatusOK, encodeEchoRequestMap(v))
}

func decodeEchoResponseBytes(data []byte) (EchoResponse, error) {
	return decodeEchoResponseJSON(json.RawMessage(data))
}

func decodeEchoResponseJSON(raw json.RawMessage) (EchoResponse, error) {
	var out EchoResponse
	m, err := httpbinder.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["message"]; ok {
		v, err := httpbinder.DecodeJSONString(raw)
		if err != nil {
			return out, httpbinder.BindError("message", "payload", "invalid string")
		}
		out.Message = v
	}
	if raw, ok := m["n"]; ok {
		v, err := httpbinder.DecodeJSONInt(raw)
		if err != nil {
			return out, httpbinder.BindError("n", "payload", "invalid int")
		}
		out.N = v
	}
	return out, nil
}

func encodeEchoResponseMap(v EchoResponse) map[string]any {
	body := map[string]any{}
	body["message"] = v.Message
	body["n"] = v.N
	return body
}

func encodeEchoResponse(w io.Writer, v EchoResponse) error {
	return json.NewEncoder(w).Encode(encodeEchoResponseMap(v))
}

func bindEchoResponse(r *http.Request) (EchoResponse, error) {
	var out EchoResponse
	var jsonBody map[string]jsonRaw
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbinder.IsJSONRequest(r) {
			m, err := httpbinder.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbinder.IsFormRequest(r) {
			m, err := httpbinder.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbinder.IsMultipartRequest(r) {
			m, _, err := httpbinder.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if qv, ok := httpbinder.QueryValue(r, "message"); ok {
		out.Message = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["message"]; ok {
			v, err := httpbinder.DecodeJSONString(raw)
			if err != nil {
				return out, httpbinder.BindError("message", "payload", "invalid string")
			}
			out.Message = v
		} else if formBody != nil {
			if fv, ok := formBody["message"]; ok {
				out.Message = fv
			}
		}
	}
	if qv, ok := httpbinder.QueryValue(r, "n"); ok {
		v, err := httpbinder.ParseInt(qv)
		if err != nil {
			return out, httpbinder.BindError("n", "query", "invalid int")
		}
		out.N = v
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["n"]; ok {
			v, err := httpbinder.DecodeJSONInt(raw)
			if err != nil {
				return out, httpbinder.BindError("n", "payload", "invalid int")
			}
			out.N = v
		} else if formBody != nil {
			if fv, ok := formBody["n"]; ok {
				v, err := httpbinder.ParseInt(fv)
				if err != nil {
					return out, httpbinder.BindError("n", "payload", "invalid int")
				}
				out.N = v
			}
		}
	}
	return out, nil
}

func writeEchoResponse(w http.ResponseWriter, r *http.Request, v EchoResponse) error {
	_ = r
	return httpbinder.WriteJSON(w, http.StatusOK, encodeEchoResponseMap(v))
}

func decodeSessionRequestBytes(data []byte) (SessionRequest, error) {
	return decodeSessionRequestJSON(json.RawMessage(data))
}

func decodeSessionRequestJSON(raw json.RawMessage) (SessionRequest, error) {
	var out SessionRequest
	_ = raw
	return out, nil
}

func encodeSessionRequestMap(v SessionRequest) map[string]any {
	body := map[string]any{}
	body["session"] = v.Session
	return body
}

func encodeSessionRequest(w io.Writer, v SessionRequest) error {
	return json.NewEncoder(w).Encode(encodeSessionRequestMap(v))
}

func bindSessionRequest(r *http.Request) (SessionRequest, error) {
	var out SessionRequest
	if cv, ok := httpbinder.CookieValue(r, "session"); ok {
		out.Session = cv
	}
	return out, nil
}

func writeSessionRequest(w http.ResponseWriter, r *http.Request, v SessionRequest) error {
	_ = r
	return httpbinder.WriteJSON(w, http.StatusOK, encodeSessionRequestMap(v))
}

func decodeSessionResponseBytes(data []byte) (SessionResponse, error) {
	return decodeSessionResponseJSON(json.RawMessage(data))
}

func decodeSessionResponseJSON(raw json.RawMessage) (SessionResponse, error) {
	var out SessionResponse
	m, err := httpbinder.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["session"]; ok {
		v, err := httpbinder.DecodeJSONString(raw)
		if err != nil {
			return out, httpbinder.BindError("session", "payload", "invalid string")
		}
		out.Session = v
	}
	if raw, ok := m["ok"]; ok {
		v, err := httpbinder.DecodeJSONBool(raw)
		if err != nil {
			return out, httpbinder.BindError("oK", "payload", "invalid bool")
		}
		out.OK = v
	}
	return out, nil
}

func encodeSessionResponseMap(v SessionResponse) map[string]any {
	body := map[string]any{}
	body["session"] = v.Session
	body["ok"] = v.OK
	return body
}

func encodeSessionResponse(w io.Writer, v SessionResponse) error {
	return json.NewEncoder(w).Encode(encodeSessionResponseMap(v))
}

func bindSessionResponse(r *http.Request) (SessionResponse, error) {
	var out SessionResponse
	var jsonBody map[string]jsonRaw
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbinder.IsJSONRequest(r) {
			m, err := httpbinder.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbinder.IsFormRequest(r) {
			m, err := httpbinder.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbinder.IsMultipartRequest(r) {
			m, _, err := httpbinder.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if qv, ok := httpbinder.QueryValue(r, "session"); ok {
		out.Session = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["session"]; ok {
			v, err := httpbinder.DecodeJSONString(raw)
			if err != nil {
				return out, httpbinder.BindError("session", "payload", "invalid string")
			}
			out.Session = v
		} else if formBody != nil {
			if fv, ok := formBody["session"]; ok {
				out.Session = fv
			}
		}
	}
	if qv, ok := httpbinder.QueryValue(r, "oK"); ok {
		v, err := httpbinder.ParseBool(qv)
		if err != nil {
			return out, httpbinder.BindError("oK", "query", "invalid bool")
		}
		out.OK = v
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["oK"]; ok {
			v, err := httpbinder.DecodeJSONBool(raw)
			if err != nil {
				return out, httpbinder.BindError("oK", "payload", "invalid bool")
			}
			out.OK = v
		} else if formBody != nil {
			if fv, ok := formBody["oK"]; ok {
				v, err := httpbinder.ParseBool(fv)
				if err != nil {
					return out, httpbinder.BindError("oK", "payload", "invalid bool")
				}
				out.OK = v
			}
		}
	}
	return out, nil
}

func writeSessionResponse(w http.ResponseWriter, r *http.Request, v SessionResponse) error {
	_ = r
	return httpbinder.WriteJSON(w, http.StatusOK, encodeSessionResponseMap(v))
}

func decodeUserGetRequestBytes(data []byte) (UserGetRequest, error) {
	return decodeUserGetRequestJSON(json.RawMessage(data))
}

func decodeUserGetRequestJSON(raw json.RawMessage) (UserGetRequest, error) {
	var out UserGetRequest
	_ = raw
	return out, nil
}

func encodeUserGetRequestMap(v UserGetRequest) map[string]any {
	body := map[string]any{}
	body["id"] = v.ID
	return body
}

func encodeUserGetRequest(w io.Writer, v UserGetRequest) error {
	return json.NewEncoder(w).Encode(encodeUserGetRequestMap(v))
}

func bindUserGetRequest(r *http.Request) (UserGetRequest, error) {
	var out UserGetRequest
	out.ID = httpbinder.PathValue(r, "id")
	return out, nil
}

func writeUserGetRequest(w http.ResponseWriter, r *http.Request, v UserGetRequest) error {
	_ = r
	return httpbinder.WriteJSON(w, http.StatusOK, encodeUserGetRequestMap(v))
}

func decodeUserGetResponseBytes(data []byte) (UserGetResponse, error) {
	return decodeUserGetResponseJSON(json.RawMessage(data))
}

func decodeUserGetResponseJSON(raw json.RawMessage) (UserGetResponse, error) {
	var out UserGetResponse
	m, err := httpbinder.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["id"]; ok {
		v, err := httpbinder.DecodeJSONString(raw)
		if err != nil {
			return out, httpbinder.BindError("iD", "payload", "invalid string")
		}
		out.ID = v
	}
	if raw, ok := m["name"]; ok {
		v, err := httpbinder.DecodeJSONString(raw)
		if err != nil {
			return out, httpbinder.BindError("name", "payload", "invalid string")
		}
		out.Name = v
	}
	return out, nil
}

func encodeUserGetResponseMap(v UserGetResponse) map[string]any {
	body := map[string]any{}
	body["id"] = v.ID
	body["name"] = v.Name
	return body
}

func encodeUserGetResponse(w io.Writer, v UserGetResponse) error {
	return json.NewEncoder(w).Encode(encodeUserGetResponseMap(v))
}

func bindUserGetResponse(r *http.Request) (UserGetResponse, error) {
	var out UserGetResponse
	var jsonBody map[string]jsonRaw
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbinder.IsJSONRequest(r) {
			m, err := httpbinder.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbinder.IsFormRequest(r) {
			m, err := httpbinder.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbinder.IsMultipartRequest(r) {
			m, _, err := httpbinder.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if qv, ok := httpbinder.QueryValue(r, "iD"); ok {
		out.ID = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["iD"]; ok {
			v, err := httpbinder.DecodeJSONString(raw)
			if err != nil {
				return out, httpbinder.BindError("iD", "payload", "invalid string")
			}
			out.ID = v
		} else if formBody != nil {
			if fv, ok := formBody["iD"]; ok {
				out.ID = fv
			}
		}
	}
	if qv, ok := httpbinder.QueryValue(r, "name"); ok {
		out.Name = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["name"]; ok {
			v, err := httpbinder.DecodeJSONString(raw)
			if err != nil {
				return out, httpbinder.BindError("name", "payload", "invalid string")
			}
			out.Name = v
		} else if formBody != nil {
			if fv, ok := formBody["name"]; ok {
				out.Name = fv
			}
		}
	}
	return out, nil
}

func writeUserGetResponse(w http.ResponseWriter, r *http.Request, v UserGetResponse) error {
	_ = r
	return httpbinder.WriteJSON(w, http.StatusOK, encodeUserGetResponseMap(v))
}

func decodeChatRequestBytes(data []byte) (ChatRequest, error) {
	return decodeChatRequestJSON(json.RawMessage(data))
}

func decodeChatRequestJSON(raw json.RawMessage) (ChatRequest, error) {
	var out ChatRequest
	m, err := httpbinder.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["message"]; ok {
		v, err := httpbinder.DecodeJSONString(raw)
		if err != nil {
			return out, httpbinder.BindError("message", "payload", "invalid string")
		}
		out.Message = v
	}
	return out, nil
}

func encodeChatRequestMap(v ChatRequest) map[string]any {
	body := map[string]any{}
	body["message"] = v.Message
	return body
}

func encodeChatRequest(w io.Writer, v ChatRequest) error {
	return json.NewEncoder(w).Encode(encodeChatRequestMap(v))
}

func bindChatRequest(r *http.Request) (ChatRequest, error) {
	var out ChatRequest
	var jsonBody map[string]jsonRaw
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbinder.IsJSONRequest(r) {
			m, err := httpbinder.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbinder.IsFormRequest(r) {
			m, err := httpbinder.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbinder.IsMultipartRequest(r) {
			m, _, err := httpbinder.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if qv, ok := httpbinder.QueryValue(r, "message"); ok {
		out.Message = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["message"]; ok {
			v, err := httpbinder.DecodeJSONString(raw)
			if err != nil {
				return out, httpbinder.BindError("message", "payload", "invalid string")
			}
			out.Message = v
		} else if formBody != nil {
			if fv, ok := formBody["message"]; ok {
				out.Message = fv
			}
		}
	}
	return out, nil
}

func writeChatRequest(w http.ResponseWriter, r *http.Request, v ChatRequest) error {
	_ = r
	return httpbinder.WriteJSON(w, http.StatusOK, encodeChatRequestMap(v))
}

func decodeChatEventBytes(data []byte) (ChatEvent, error) {
	return decodeChatEventJSON(json.RawMessage(data))
}

func decodeChatEventJSON(raw json.RawMessage) (ChatEvent, error) {
	var out ChatEvent
	m, err := httpbinder.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["type"]; ok {
		v, err := httpbinder.DecodeJSONString(raw)
		if err != nil {
			return out, httpbinder.BindError("type", "payload", "invalid string")
		}
		out.Type = v
	}
	if raw, ok := m["delta"]; ok {
		v, err := httpbinder.DecodeJSONString(raw)
		if err != nil {
			return out, httpbinder.BindError("delta", "payload", "invalid string")
		}
		out.Delta = v
	}
	return out, nil
}

func encodeChatEventMap(v ChatEvent) map[string]any {
	body := map[string]any{}
	body["type"] = v.Type
	body["delta"] = v.Delta
	return body
}

func encodeChatEvent(w io.Writer, v ChatEvent) error {
	return json.NewEncoder(w).Encode(encodeChatEventMap(v))
}

func bindChatEvent(r *http.Request) (ChatEvent, error) {
	var out ChatEvent
	var jsonBody map[string]jsonRaw
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbinder.IsJSONRequest(r) {
			m, err := httpbinder.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbinder.IsFormRequest(r) {
			m, err := httpbinder.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbinder.IsMultipartRequest(r) {
			m, _, err := httpbinder.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if qv, ok := httpbinder.QueryValue(r, "type"); ok {
		out.Type = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["type"]; ok {
			v, err := httpbinder.DecodeJSONString(raw)
			if err != nil {
				return out, httpbinder.BindError("type", "payload", "invalid string")
			}
			out.Type = v
		} else if formBody != nil {
			if fv, ok := formBody["type"]; ok {
				out.Type = fv
			}
		}
	}
	if qv, ok := httpbinder.QueryValue(r, "delta"); ok {
		out.Delta = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["delta"]; ok {
			v, err := httpbinder.DecodeJSONString(raw)
			if err != nil {
				return out, httpbinder.BindError("delta", "payload", "invalid string")
			}
			out.Delta = v
		} else if formBody != nil {
			if fv, ok := formBody["delta"]; ok {
				out.Delta = fv
			}
		}
	}
	return out, nil
}

func writeChatEvent(w http.ResponseWriter, r *http.Request, v ChatEvent) error {
	_ = r
	return httpbinder.WriteJSON(w, http.StatusOK, encodeChatEventMap(v))
}

func decodeHealthResponseBytes(data []byte) (HealthResponse, error) {
	return decodeHealthResponseJSON(json.RawMessage(data))
}

func decodeHealthResponseJSON(raw json.RawMessage) (HealthResponse, error) {
	var out HealthResponse
	m, err := httpbinder.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["status"]; ok {
		v, err := httpbinder.DecodeJSONString(raw)
		if err != nil {
			return out, httpbinder.BindError("status", "payload", "invalid string")
		}
		out.Status = v
	}
	return out, nil
}

func encodeHealthResponseMap(v HealthResponse) map[string]any {
	body := map[string]any{}
	body["status"] = v.Status
	return body
}

func encodeHealthResponse(w io.Writer, v HealthResponse) error {
	return json.NewEncoder(w).Encode(encodeHealthResponseMap(v))
}

func bindHealthResponse(r *http.Request) (HealthResponse, error) {
	var out HealthResponse
	var jsonBody map[string]jsonRaw
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbinder.IsJSONRequest(r) {
			m, err := httpbinder.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbinder.IsFormRequest(r) {
			m, err := httpbinder.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbinder.IsMultipartRequest(r) {
			m, _, err := httpbinder.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if qv, ok := httpbinder.QueryValue(r, "status"); ok {
		out.Status = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["status"]; ok {
			v, err := httpbinder.DecodeJSONString(raw)
			if err != nil {
				return out, httpbinder.BindError("status", "payload", "invalid string")
			}
			out.Status = v
		} else if formBody != nil {
			if fv, ok := formBody["status"]; ok {
				out.Status = fv
			}
		}
	}
	return out, nil
}

func writeHealthResponse(w http.ResponseWriter, r *http.Request, v HealthResponse) error {
	_ = r
	return httpbinder.WriteJSON(w, http.StatusOK, encodeHealthResponseMap(v))
}
